from ..context.device import DeviceType as DeviceType
from .controller import ControleMode as ControleMode, Controller as Controller

class CollectiveController(Controller):
    def __init__(self, ctx) -> None: ...
    @classmethod
    def enable(cls, ctx): ...
    def build_pod(self): ...

class CollectiveElasticController(CollectiveController):
    @classmethod
    def enable(cls, ctx): ...
    def register(self) -> None: ...
    def run(self) -> None: ...
