from .collective import CollectiveController as CollectiveController, ControleMode as ControleMode
from _typeshed import Incomplete
from paddle.distributed.launch.job.container import Container as Container

class IPUController(CollectiveController):
    @classmethod
    def enable(cls, ctx): ...
    def parse_ipu_args(self, args_list): ...
    def replace_training_script(self) -> None: ...
    def new_container(self, entrypoint: Incomplete | None = None, envs={}, use_ctx_env: bool = True, out: Incomplete | None = None, err: Incomplete | None = None): ...
    def run(self) -> None: ...
