from .static_flops import Table as Table, static_flops as static_flops
from _typeshed import Incomplete
from paddle import nn as nn
from paddle.jit.dy2static.program_translator import unwrap_decorators as unwrap_decorators

def flops(net, input_size, custom_ops: Incomplete | None = None, print_detail: bool = False): ...
def count_convNd(m, x, y) -> None: ...
def count_leaky_relu(m, x, y) -> None: ...
def count_bn(m, x, y) -> None: ...
def count_linear(m, x, y) -> None: ...
def count_avgpool(m, x, y) -> None: ...
def count_adap_avgpool(m, x, y) -> None: ...
def count_zero_ops(m, x, y) -> None: ...
def count_parameters(m, x, y) -> None: ...
def count_io_info(m, x, y) -> None: ...

register_hooks: Incomplete

def dynamic_flops(model, inputs, custom_ops: Incomplete | None = None, print_detail: bool = False): ...
