from _typeshed import Incomplete

class ProgressBar:
    file: Incomplete
    name: Incomplete
    def __init__(self, num: Incomplete | None = None, width: int = 30, verbose: int = 1, start: bool = True, file=..., name: str = 'step') -> None: ...
    def start(self) -> None: ...
    def update(self, current_num, values={}): ...
