from ..base.data_feeder import check_type as check_type, check_variable_and_dtype as check_variable_and_dtype
from ..base.framework import in_pir_mode as in_pir_mode
from ..common_ops_import import Variable as Variable
from ..framework import LayerHelper as LayerHelper, core as core, in_dynamic_mode as in_dynamic_mode
from _typeshed import Incomplete

def array_length(array): ...
def array_read(array, i): ...
def array_write(x, i, array: Incomplete | None = None): ...
def create_array(dtype, initialized_list: Incomplete | None = None): ...
