from ..base.data_feeder import check_type as check_type, check_variable_and_dtype as check_variable_and_dtype
from ..base.framework import in_dynamic_or_pir_mode as in_dynamic_or_pir_mode, in_pir_mode as in_pir_mode
from ..common_ops_import import Variable as Variable
from ..framework import LayerHelper as LayerHelper, core as core
from .creation import assign as assign
from _typeshed import Incomplete

def rank(input): ...
def shape(input): ...
def is_complex(x): ...
def is_floating_point(x): ...
def is_integer(x): ...
def real(x, name: Incomplete | None = None): ...
def imag(x, name: Incomplete | None = None): ...
