from ..base.data_feeder import check_dtype as check_dtype, check_type as check_type, check_variable_and_dtype as check_variable_and_dtype, convert_dtype as convert_dtype
from ..base.framework import Variable as Variable
from ..framework import LayerHelper as LayerHelper, convert_np_dtype_to_dtype_ as convert_np_dtype_to_dtype_, core as core, dygraph_only as dygraph_only, in_dynamic_mode as in_dynamic_mode, in_dynamic_or_pir_mode as in_dynamic_or_pir_mode, in_pir_mode as in_pir_mode
from .creation import zeros as zeros
from _typeshed import Incomplete
from paddle.tensor import fill_constant as fill_constant
from paddle.utils.inplace_utils import inplace_apis_in_dygraph_only as inplace_apis_in_dygraph_only

def tensor_array_to_tensor(input, axis: int = 1, use_stack: bool = False, name: Incomplete | None = None): ...
def cast(x, dtype): ...
def cast_(x, dtype): ...
def slice(input, axes, starts, ends): ...
def transpose(x, perm, name: Incomplete | None = None): ...
def unstack(x, axis: int = 0, num: Incomplete | None = None): ...
def shard_index(input, index_num, nshards, shard_id, ignore_value: int = -1): ...
def crop(x, shape: Incomplete | None = None, offsets: Incomplete | None = None, name: Incomplete | None = None): ...
def fill_(x, value): ...
def zero_(x): ...
def fill_diagonal_(x, value, offset: int = 0, wrap: bool = False, name: Incomplete | None = None): ...
def fill_diagonal_tensor_(x, y, offset: int = 0, dim1: int = 0, dim2: int = 1, name: Incomplete | None = None): ...
def fill_diagonal_tensor(x, y, offset: int = 0, dim1: int = 0, dim2: int = 1, name: Incomplete | None = None): ...
def tolist(x): ...
def concat(x, axis: int = 0, name: Incomplete | None = None): ...
def broadcast_tensors(input, name: Incomplete | None = None): ...
def flip(x, axis, name: Incomplete | None = None): ...
def rot90(x, k: int = 1, axes=[0, 1], name: Incomplete | None = None): ...
def flatten(x, start_axis: int = 0, stop_axis: int = -1, name: Incomplete | None = None): ...
def flatten_(x, start_axis: int = 0, stop_axis: int = -1, name: Incomplete | None = None): ...
def roll(x, shifts, axis: Incomplete | None = None, name: Incomplete | None = None): ...
def stack(x, axis: int = 0, name: Incomplete | None = None): ...
def split(x, num_or_sections, axis: int = 0, name: Incomplete | None = None): ...
def vsplit(x, num_or_sections, name: Incomplete | None = None): ...
def squeeze(x, axis: Incomplete | None = None, name: Incomplete | None = None): ...
def squeeze_(x, axis: Incomplete | None = None, name: Incomplete | None = None): ...
def unique_consecutive(x, return_inverse: bool = False, return_counts: bool = False, axis: Incomplete | None = None, dtype: str = 'int64', name: Incomplete | None = None): ...
def unique(x, return_index: bool = False, return_inverse: bool = False, return_counts: bool = False, axis: Incomplete | None = None, dtype: str = 'int64', name: Incomplete | None = None): ...
def unsqueeze(x, axis, name: Incomplete | None = None): ...
def unsqueeze_(x, axis, name: Incomplete | None = None): ...
def gather(x, index, axis: Incomplete | None = None, name: Incomplete | None = None): ...
def unbind(input, axis: int = 0): ...
def scatter(x, index, updates, overwrite: bool = True, name: Incomplete | None = None): ...
def scatter_(x, index, updates, overwrite: bool = True, name: Incomplete | None = None): ...
def scatter_nd_add(x, index, updates, name: Incomplete | None = None): ...
def scatter_nd(index, updates, shape, name: Incomplete | None = None): ...
def chunk(x, chunks, axis: int = 0, name: Incomplete | None = None): ...
def tile(x, repeat_times, name: Incomplete | None = None): ...
def expand_as(x, y, name: Incomplete | None = None): ...
def broadcast_to(x, shape, name: Incomplete | None = None): ...
def expand(x, shape, name: Incomplete | None = None): ...
def reshape(x, shape, name: Incomplete | None = None): ...
def reshape_(x, shape, name: Incomplete | None = None): ...
def atleast_1d(*inputs, name: Incomplete | None = None): ...
def atleast_2d(*inputs, name: Incomplete | None = None): ...
def atleast_3d(*inputs, name: Incomplete | None = None): ...
def gather_nd(x, index, name: Incomplete | None = None): ...
def strided_slice(x, axes, starts, ends, strides, name: Incomplete | None = None): ...
def tensordot(x, y, axes: int = 2, name: Incomplete | None = None): ...
def as_complex(x, name: Incomplete | None = None): ...
def as_real(x, name: Incomplete | None = None): ...
def repeat_interleave(x, repeats, axis: Incomplete | None = None, name: Incomplete | None = None): ...
def moveaxis(x, source, destination, name: Incomplete | None = None): ...
def masked_fill(x, mask, value, name: Incomplete | None = None): ...
def masked_fill_(x, mask, value, name: Incomplete | None = None): ...
def non_negative_axis(arr, axis): ...
def infer_broadcast_shape(arr, indices, axis): ...
def take_along_axis(arr, indices, axis, broadcast: bool = True): ...
def put_along_axis(arr, indices, values, axis, reduce: str = 'assign', include_self: bool = True, broadcast: bool = True): ...
def put_along_axis_(arr, indices, values, axis, reduce: str = 'assign', include_self: bool = True): ...
def index_add(x, index, axis, value, name: Incomplete | None = None): ...
def index_add_(x, index, axis, value, name: Incomplete | None = None): ...
def index_put_(x, indices, value, accumulate: bool = False, name: Incomplete | None = None): ...
def index_put(x, indices, value, accumulate: bool = False, name: Incomplete | None = None): ...
def unflatten(x, axis, shape, name: Incomplete | None = None): ...
def as_strided(x, shape, stride, offset: int = 0, name: Incomplete | None = None): ...
def view(x, shape_or_dtype, name: Incomplete | None = None): ...
def view_as(x, other, name: Incomplete | None = None): ...
def unfold(x, axis, size, step, name: Incomplete | None = None): ...
def index_fill(x, index, axis, value, name: Incomplete | None = None): ...
def index_fill_(x, index, axis, value, name: Incomplete | None = None): ...
def diagonal_scatter(x, y, offset: int = 0, axis1: int = 0, axis2: int = 1, name: Incomplete | None = None): ...
def select_scatter(x, values, axis, index, name: Incomplete | None = None): ...
