from ..base.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from ..framework import LayerHelper as LayerHelper, in_dynamic_or_pir_mode as in_dynamic_or_pir_mode
from .layer_function_generator import add_sample_code as add_sample_code, generate_activation_fn as generate_activation_fn, generate_inplace_fn as generate_inplace_fn, generate_layer_fn as generate_layer_fn
from _typeshed import Incomplete
from paddle.utils.inplace_utils import inplace_apis_in_dygraph_only as inplace_apis_in_dygraph_only

__deprecated_func_name__: Incomplete
__activations_noattr__: Incomplete
__unary_func__: Incomplete
__inplace_unary_func__: Incomplete
func: Incomplete

def acos(x, name: Incomplete | None = None): ...
def acosh(x, name: Incomplete | None = None): ...
def asin(x, name: Incomplete | None = None): ...
def asinh(x, name: Incomplete | None = None): ...
def atan(x, name: Incomplete | None = None): ...
def atanh(x, name: Incomplete | None = None): ...
def ceil(x, name: Incomplete | None = None): ...
def cos(x, name: Incomplete | None = None): ...
def cosh(x, name: Incomplete | None = None): ...
def exp(x, name: Incomplete | None = None): ...
def expm1(x, name: Incomplete | None = None): ...
def floor(x, name: Incomplete | None = None): ...
def reciprocal(x, name: Incomplete | None = None): ...
def round(x, name: Incomplete | None = None): ...
def rsqrt(x, name: Incomplete | None = None): ...
def sigmoid(x, name: Incomplete | None = None): ...
def sin(x, name: Incomplete | None = None): ...
def sinh(x, name: Incomplete | None = None): ...
def sqrt(x, name: Incomplete | None = None): ...
def square(x, name: Incomplete | None = None): ...
def tan(x, name: Incomplete | None = None): ...
def erf(x, name: Incomplete | None = None): ...
