from ..base.data_feeder import check_type as check_type, check_variable_and_dtype as check_variable_and_dtype
from ..common_ops_import import Variable as Variable
from ..framework import LayerHelper as LayerHelper, core as core
from .search import where as where
from _typeshed import Incomplete
from paddle.base.libpaddle import DataType as DataType
from paddle.framework import in_dynamic_mode as in_dynamic_mode, in_dynamic_or_pir_mode as in_dynamic_or_pir_mode

def mean(x, axis: Incomplete | None = None, keepdim: bool = False, name: Incomplete | None = None): ...
def var(x, axis: Incomplete | None = None, unbiased: bool = True, keepdim: bool = False, name: Incomplete | None = None): ...
def std(x, axis: Incomplete | None = None, unbiased: bool = True, keepdim: bool = False, name: Incomplete | None = None): ...
def numel(x, name: Incomplete | None = None): ...
def nanmedian(x, axis: Incomplete | None = None, keepdim: bool = False, name: Incomplete | None = None): ...
def median(x, axis: Incomplete | None = None, keepdim: bool = False, name: Incomplete | None = None): ...
def quantile(x, q, axis: Incomplete | None = None, keepdim: bool = False): ...
def nanquantile(x, q, axis: Incomplete | None = None, keepdim: bool = False): ...
