from paddle import Tensor as Tensor

def hz_to_mel(freq: Tensor | float, htk: bool = False) -> Tensor | float: ...
def mel_to_hz(mel: float | Tensor, htk: bool = False) -> float | Tensor: ...
def mel_frequencies(n_mels: int = 64, f_min: float = 0.0, f_max: float = 11025.0, htk: bool = False, dtype: str = 'float32') -> Tensor: ...
def fft_frequencies(sr: int, n_fft: int, dtype: str = 'float32') -> Tensor: ...
def compute_fbank_matrix(sr: int, n_fft: int, n_mels: int = 64, f_min: float = 0.0, f_max: float | None = None, htk: bool = False, norm: str | float = 'slaney', dtype: str = 'float32') -> Tensor: ...
def power_to_db(spect: Tensor, ref_value: float = 1.0, amin: float = 1e-10, top_db: float | None = 80.0) -> Tensor: ...
def create_dct(n_mfcc: int, n_mels: int, norm: str | None = 'ortho', dtype: str = 'float32') -> Tensor: ...
