from _typeshed import Incomplete
from paddle import Tensor as Tensor

class WindowFunctionRegister:
    def __init__(self) -> None: ...
    def register(self, func: Incomplete | None = None): ...
    def get(self, name): ...

window_function_register: Incomplete

def get_window(window: str | tuple[str, float], win_length: int, fftbins: bool = True, dtype: str = 'float64') -> Tensor: ...
