from .unary import cast as cast
from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.framework import core as core, dygraph_only as dygraph_only
from paddle.base.layer_helper import LayerHelper as LayerHelper

def matmul(x, y, name: Incomplete | None = None): ...
def masked_matmul(x, y, mask, name: Incomplete | None = None): ...
def mv(x, vec, name: Incomplete | None = None): ...
def add(x, y, name: Incomplete | None = None): ...
def subtract(x, y, name: Incomplete | None = None): ...
def multiply(x, y, name: Incomplete | None = None): ...
def divide(x, y, name: Incomplete | None = None): ...
def is_same_shape(x, y): ...
