from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.data_feeder import check_type as check_type, check_variable_and_dtype as check_variable_and_dtype
from paddle.base.framework import convert_np_dtype_to_dtype_ as convert_np_dtype_to_dtype_, core as core, dygraph_only as dygraph_only
from paddle.common_ops_import import Variable as Variable
from paddle.framework import LayerHelper as LayerHelper

def sin(x, name: Incomplete | None = None): ...
def tan(x, name: Incomplete | None = None): ...
def asin(x, name: Incomplete | None = None): ...
def transpose(x, perm, name: Incomplete | None = None): ...
def sum(x, axis: Incomplete | None = None, dtype: Incomplete | None = None, keepdim: bool = False, name: Incomplete | None = None): ...
def atan(x, name: Incomplete | None = None): ...
def sinh(x, name: Incomplete | None = None): ...
def asinh(x, name: Incomplete | None = None): ...
def atanh(x, name: Incomplete | None = None): ...
def tanh(x, name: Incomplete | None = None): ...
def square(x, name: Incomplete | None = None): ...
def sqrt(x, name: Incomplete | None = None): ...
def log1p(x, name: Incomplete | None = None): ...
def cast(x, index_dtype: Incomplete | None = None, value_dtype: Incomplete | None = None, name: Incomplete | None = None): ...
def pow(x, factor, name: Incomplete | None = None): ...
def neg(x, name: Incomplete | None = None): ...
def abs(x, name: Incomplete | None = None): ...
def coalesce(x, name: Incomplete | None = None): ...
def rad2deg(x, name: Incomplete | None = None): ...
def deg2rad(x, name: Incomplete | None = None): ...
def expm1(x, name: Incomplete | None = None): ...
def reshape(x, shape, name: Incomplete | None = None): ...
def isnan(x, name: Incomplete | None = None): ...
def slice(x, axes, starts, ends, name: Incomplete | None = None): ...
def pca_lowrank(x, q: Incomplete | None = None, center: bool = True, niter: int = 2, name: Incomplete | None = None): ...
