from paddle.distributed.fleet.launch_utils import get_cluster as get_cluster, logger as logger

def get_cloud_cluster(args_node_ips, device_mode, devices_per_proc, args_port: int = 6170): ...
def use_paddlecloud(): ...
def get_trainers_num(): ...
