from _typeshed import Incomplete
from paddle.distributed.fleet.elastic.manager import LauncherInterface as LauncherInterface
from paddle.distributed.fleet.launch_utils import logger as logger, pull_worker_log as pull_worker_log, start_local_trainers as start_local_trainers

class CollectiveLauncher(LauncherInterface):
    args: Incomplete
    procs: Incomplete
    def __init__(self, args) -> None: ...
    tmp_dir: Incomplete
    def launch(self) -> None: ...
    def stop(self) -> None: ...
    def watch(self): ...
