import paddle
from .backend import AudioInfo as AudioInfo
from pathlib import Path

def info(filepath: str) -> AudioInfo: ...
def load(filepath: str | Path, frame_offset: int = 0, num_frames: int = -1, normalize: bool = True, channels_first: bool = True) -> tuple[paddle.Tensor, int]: ...
def save(filepath: str, src: paddle.Tensor, sample_rate: int, channels_first: bool = True, encoding: str | None = None, bits_per_sample: int | None = 16): ...
