from .instruction_utils import instrs_info as instrs_info
from .stack_analyse import StackAnalyser as StackAnalyser
from paddle.jit.sot.utils import log as log, log_do as log_do

def apply_instr_pass(instrs, code_options): ...
def find_stored_once_local_vars(instrs, code_options): ...
def find_loaded_once_local_vars(instrs, code_options): ...
def find_related_local_opcodes(instrs, code_options): ...
def remove_load_store_pass(instrs, code_options): ...
def remove_duplicate_resume(instrs, code_options): ...
