from ...utils import Singleton as Singleton

class StackAnalyser:
    def stack_effect(self, instr): ...
    def LOAD_GLOBAL(self, instr): ...
    def LOAD_CONST(self, instr): ...
    def LOAD_FAST(self, instr): ...
    def LOAD_ATTR(self, instr): ...
    def LOAD_METHOD(self, instr): ...
    def STORE_FAST(self, instr): ...
    def BUILD_TUPLE(self, instr): ...
    def BUILD_LIST(self, instr): ...
    def BUILD_SLICE(self, instr): ...
    def UNPACK_SEQUENCE(self, instr): ...
    def CALL_FUNCTION(self, instr): ...
    def DUP_TOP(self, instr): ...
    def DUP_TOP_TWO(self, instr): ...
    def ROT_N(self, instr): ...
    def ROT_TWO(self, instr): ...
    def ROT_THREE(self, instr): ...
    def ROT_FOUR(self, instr): ...
    def GET_ITER(self, instr): ...
    def POP_TOP(self, instr): ...
    def PUSH_NULL(self, instr): ...
    def NOP(self, instr): ...
    def EXTENDED_ARG(self, instr): ...
