from ...utils import BreakGraphError as BreakGraphError, FallbackError as FallbackError

def raise_break_graph_fn(*args, **kwarg) -> None: ...
def raise_not_implement_fn(*args, **kwarg) -> None: ...
def operator_in(left, right): ...
def operator_not_in(left, right): ...
def operator_exception_match(left, right) -> None: ...
def operator_BAD(left, right) -> None: ...
def operator_is_none(val) -> None: ...
def operator_is_not_none(val) -> None: ...
def tensor_numel(x) -> None: ...
