from ...infer_meta import InferMetaCache as InferMetaCache, LayerInferMetaCache as LayerInferMetaCache, MetaInfo as MetaInfo
from ...profiler import EventGuard as EventGuard, event_register as event_register
from ...symbolic.statement_ir import Reference as Reference, Symbol as Symbol
from ...symbolic.symbolic_context import SymbolicTraceContext as SymbolicTraceContext
from ...utils import ENV_SHOW_TRACKERS as ENV_SHOW_TRACKERS, NameGenerator as NameGenerator, OrderedSet as OrderedSet, inner_error_default_handler as inner_error_default_handler, is_inplace_api as is_inplace_api, is_paddle_api as is_paddle_api, log as log, log_do as log_do, map_if as map_if, tmp_name_guard as tmp_name_guard
from ..instruction_utils import get_instructions as get_instructions
from .guard import Guard as Guard, StringifyExpression as StringifyExpression, make_guard as make_guard
from .mutable_data import MutationDel as MutationDel, MutationNew as MutationNew, MutationSet as MutationSet
from .pycode_generator import PyCodeGen as PyCodeGen
from .side_effects import DictSideEffectRestorer as DictSideEffectRestorer, GlobalDelSideEffectRestorer as GlobalDelSideEffectRestorer, GlobalSetSideEffectRestorer as GlobalSetSideEffectRestorer, ListSideEffectRestorer as ListSideEffectRestorer, ObjDelSideEffectRestorer as ObjDelSideEffectRestorer, ObjSetSideEffectRestorer as ObjSetSideEffectRestorer, SideEffectRestorer as SideEffectRestorer, SideEffects as SideEffects
from .tracker import BuiltinTracker as BuiltinTracker, DummyTracker as DummyTracker
from .variables import DictVariable as DictVariable, GlobalVariable as GlobalVariable, ListVariable as ListVariable, NullVariable as NullVariable, PaddleLayerVariable as PaddleLayerVariable, TensorVariable as TensorVariable, VariableBase as VariableBase, VariableFactory as VariableFactory, find_traceable_vars as find_traceable_vars, map_variables as map_variables
from _typeshed import Incomplete
from functools import cached_property as cached_property
from typing import Any, Callable, NamedTuple

def convert_to_meta(inputs: Any): ...
def convert_to_symbol(inputs: Any): ...

class FunctionGraph:
    OUT_VAR_PREFIX: str

    class Memo(NamedTuple):
        inner_out: Incomplete
        input_variables: Incomplete
        stmt_ir: Incomplete
        global_guards: Incomplete
        side_effects_state: Incomplete
        print_variables: Incomplete
        inplace_tensors: Incomplete
    sir_ctx: Incomplete
    inner_out: Incomplete
    input_variables: Incomplete
    pycode_gen: Incomplete
    side_effects: Incomplete
    build_strategy: Incomplete
    def __init__(self, frame, **kwargs) -> None: ...
    def add_print_variables(self, variable) -> None: ...
    def add_inplace_tensors(self, variable) -> None: ...
    def need_add_input(self, var): ...
    def save_memo(self) -> FunctionGraph.Memo: ...
    def restore_memo(self, memo: FunctionGraph.Memo): ...
    def collect_input_variables(self, inputs: list[VariableBase]): ...
    @property
    def guard_fn(self) -> Guard: ...
    def start_compile(self, *ret_vars: VariableBase): ...
    def call_paddle_api(self, func: Callable[..., Any], *args: VariableBase, **kwargs: VariableBase): ...
    def call_tensor_method(self, method_name: str, *args: VariableBase, **kwargs): ...
    @staticmethod
    def get_opcode_executor_stack(): ...
    def call_layer(self, layer: PaddleLayerVariable, weak_ref: bool, *args: VariableBase, **kwargs: VariableBase): ...
    def symbolic_call(self, infer_meta_fn, compute_fn, func, *args, **kwargs): ...
    def add_global_guarded_variable(self, variable: VariableBase): ...
    def remove_global_guarded_variable(self, variable: VariableBase): ...
    def restore_print_stmts(self, variables: list[VariableBase]): ...
    def restore_inplace_tensor(self, variables: list[VariableBase]): ...
    def restore_side_effects(self, variables: list[VariableBase]): ...
