from _typeshed import Incomplete
from paddle.base.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from paddle.base.layer_helper import LayerHelper as LayerHelper
from paddle.framework import in_dynamic_or_pir_mode as in_dynamic_or_pir_mode
from paddle.utils import deprecated as deprecated

def segment_sum(data, segment_ids, name: Incomplete | None = None): ...
def segment_mean(data, segment_ids, name: Incomplete | None = None): ...
def segment_min(data, segment_ids, name: Incomplete | None = None): ...
def segment_max(data, segment_ids, name: Incomplete | None = None): ...
