from ..dy2static.program_translator import synchronized as synchronized
from _typeshed import Incomplete

class ParametersRecorder:
    params_dict: Incomplete
    tensor2opresult: Incomplete
    def __init__(self) -> None: ...
    def get(self, program, tensor): ...
    def pop(self, program): ...

class InplaceMap:
    params_dict: Incomplete
    def __init__(self) -> None: ...
    def add(self, program, id, param) -> None: ...
    def get(self, program, id): ...
    def restore_checkpoint(self, checkpoint) -> None: ...
    def save_checkpoint(self): ...
