from _typeshed import Incomplete

__all__ = ['grad', 'calc_gradient', 'calc_gradient_helper']

def calc_gradient_helper(outputs, inputs, grad_outputs, no_grad_set): ...
def calc_gradient(outputs, inputs, grad_outputs, no_grad_set): ...
def grad(outputs, inputs, grad_outputs: Incomplete | None = None, retain_graph: Incomplete | None = None, create_graph: bool = False, only_inputs: bool = True, allow_unused: bool = False, no_grad_vars: Incomplete | None = None): ...
