from _typeshed import Incomplete
from paddle.framework import in_dynamic_mode as in_dynamic_mode

def count_by_gate(gate, num_expert, world_size, require_pos: bool = True, group: Incomplete | None = None): ...
def limit_by_capacity(topk_idx, num_expert, world_size, capacity, group: Incomplete | None = None): ...
