from .metadata import LocalTensorIndex as LocalTensorIndex, LocalTensorMetadata as LocalTensorMetadata, Metadata as Metadata
from .utils import compute_local_shape_and_global_offset as compute_local_shape_and_global_offset, flatten_state_dict as flatten_state_dict
from _typeshed import Incomplete
from paddle.distributed.communication.group import is_initialized as is_initialized
from paddle.distributed.fleet.utils.log_util import logger as logger

def check_state_dict(state_dict, process_group) -> None: ...
def check_file_name(file_name, process_group) -> None: ...
def merge_state_dict_metadata(global_state_dict_metadata): ...
def dedup_storage_metadata(global_storage_metadata): ...
def save_state_dict(state_dict, path, process_group: Incomplete | None = None, coordinator_rank: int = 0) -> None: ...
