import numpy as np
from paddle.framework import core as core

def get_coordinator(mesh: np.array | list[list[int]], rank: int): ...
def compute_local_shape_and_global_offset(global_shape: list[int], process_mesh: core.ProcessMesh, dims_mapping: list[int]) -> tuple[tuple[int], tuple[int]]: ...
def flatten_state_dict(state_dict): ...
