from _typeshed import Incomplete
from paddle.base.proto import data_feed_pb2 as data_feed_pb2

class DataFeedDesc:
    proto_desc: Incomplete
    def __init__(self, proto_file) -> None: ...
    def set_batch_size(self, batch_size) -> None: ...
    def set_dense_slots(self, dense_slots_name) -> None: ...
    def set_use_slots(self, use_slots_name) -> None: ...
    def desc(self): ...
