from _typeshed import Incomplete

__tl_scope__: Incomplete

def get_cur_scope(): ...
def enter_local_scope() -> None: ...
def leave_local_scope() -> None: ...
def var(name): ...
def find_var(name): ...
def scoped_function(func) -> None: ...
