from . import core as core
from .data_feeder import DataToLoDTensorConverter as DataToLoDTensorConverter

def create_lod_tensor(data, recursive_seq_lens, place): ...
def create_random_int_lodtensor(recursive_seq_lens, base_shape, place, low, high): ...
