from . import core as core, unique_name as unique_name
from _typeshed import Incomplete

MAX_INTEGER: Incomplete

def replace_ellipsis(var, item): ...
def replace_ndarray_and_range(item): ...
def replace_none(item): ...
def is_integer_or_scalar_tensor(ele): ...
def is_bool_tensor(ele): ...
def deal_attrs(attrs, attr, attr_name, tensor_attr_name, inputs, infer_flags) -> None: ...
def get_value_for_bool_tensor(var, item): ...
def deal_advanced_index(ori_tensor, indices, is_for_setitem, values, out_is_view: bool = True): ...
def parse_index(x, indices): ...
def get_tensor_with_basic_indexing(x, axes, starts, ends, steps, decrease_axes, none_axes, use_strided_slice): ...
def parse_bool_and_broadcast_indices(indices): ...
