from ..base_observer import BaseObserver as BaseObserver
from ..factory import ObserverFactory as ObserverFactory
from _typeshed import Incomplete

class AbsmaxObserver(ObserverFactory):
    def __init__(self, quant_bits: int = 8) -> None: ...

class AbsmaxObserverLayer(BaseObserver):
    INIT_ABS_MAX: float
    abs_max_val: Incomplete
    def __init__(self, layer, quant_bits: int = 8) -> None: ...
    def forward(self, input): ...
    thresholds: Incomplete
    def cal_thresholds(self) -> None: ...
    def bit_length(self): ...
    def quant_axis(self): ...
    def scales(self): ...
    def zero_points(self) -> None: ...
