from _typeshed import Incomplete
from paddle.base.data_feeder import check_type as check_type, convert_dtype as convert_dtype
from paddle.base.framework import Variable as Variable
from paddle.distribution import distribution as distribution
from paddle.framework import in_dynamic_mode as in_dynamic_mode
from paddle.tensor import multinomial as multinomial

class Categorical(distribution.Distribution):
    name: Incomplete
    dtype: str
    logits: Incomplete
    def __init__(self, logits, name: Incomplete | None = None) -> None: ...
    def sample(self, shape): ...
    def kl_divergence(self, other): ...
    def entropy(self): ...
    def probs(self, value): ...
    def log_prob(self, value): ...
