from _typeshed import Incomplete
from paddle.base import framework as framework
from paddle.distribution import distribution as distribution

class Cauchy(distribution.Distribution):
    name: Incomplete
    dtype: Incomplete
    def __init__(self, loc, scale, name: Incomplete | None = None) -> None: ...
    @property
    def mean(self) -> None: ...
    @property
    def variance(self) -> None: ...
    @property
    def stddev(self) -> None: ...
    def sample(self, shape, name: Incomplete | None = None): ...
    def rsample(self, shape, name: Incomplete | None = None): ...
    def prob(self, value): ...
    def log_prob(self, value): ...
    def cdf(self, value): ...
    def entropy(self): ...
    def kl_divergence(self, other): ...
