from _typeshed import Incomplete
from paddle.base.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from paddle.base.layer_helper import LayerHelper as LayerHelper
from paddle.distribution import exponential_family as exponential_family
from paddle.framework import in_dynamic_mode as in_dynamic_mode

class Dirichlet(exponential_family.ExponentialFamily):
    concentration: Incomplete
    def __init__(self, concentration) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    def sample(self, shape=()): ...
    def prob(self, value): ...
    def log_prob(self, value): ...
    def entropy(self): ...
