from paddle.base.data_feeder import check_variable_and_dtype as check_variable_and_dtype, convert_dtype as convert_dtype
from paddle.base.framework import Variable as Variable
from paddle.framework import in_dynamic_mode as in_dynamic_mode

class Distribution:
    def __init__(self, batch_shape=(), event_shape=()) -> None: ...
    @property
    def batch_shape(self): ...
    @property
    def event_shape(self): ...
    @property
    def mean(self) -> None: ...
    @property
    def variance(self) -> None: ...
    def sample(self, shape=()) -> None: ...
    def rsample(self, shape=()) -> None: ...
    def entropy(self) -> None: ...
    def kl_divergence(self, other) -> None: ...
    def prob(self, value): ...
    def log_prob(self, value) -> None: ...
    def probs(self, value) -> None: ...
