from _typeshed import Incomplete
from paddle.base import framework as framework
from paddle.distribution import distribution as distribution

class Geometric(distribution.Distribution):
    probs: Incomplete
    def __init__(self, probs) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    @property
    def stddev(self): ...
    def pmf(self, k): ...
    def log_pmf(self, k): ...
    def sample(self, shape=()): ...
    def rsample(self, shape=()): ...
    def entropy(self): ...
    def cdf(self, k): ...
    def kl_divergence(self, other): ...
