from _typeshed import Incomplete
from paddle.base import framework as framework
from paddle.distribution.transformed_distribution import TransformedDistribution as TransformedDistribution

class Gumbel(TransformedDistribution):
    base_dist: Incomplete
    transforms: Incomplete
    def __init__(self, loc, scale) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    @property
    def stddev(self): ...
    def prob(self, value): ...
    def log_prob(self, value): ...
    def cdf(self, value): ...
    def entropy(self): ...
    def sample(self, shape): ...
    def rsample(self, shape): ...
