from paddle.distribution import distribution as distribution

class Independent(distribution.Distribution):
    def __init__(self, base, reinterpreted_batch_rank) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    def sample(self, shape=()): ...
    def log_prob(self, value): ...
    def prob(self, value): ...
    def entropy(self): ...
