from _typeshed import Incomplete

__all__ = ['register_kl', 'kl_divergence']

def kl_divergence(p, q): ...
def register_kl(cls_p, cls_q): ...

class _Compare:
    classes: Incomplete
    def __init__(self, *classes) -> None: ...
    def __eq__(self, other): ...
    def __le__(self, other): ...
