from paddle.base import framework as framework
from paddle.distribution import distribution as distribution

class Laplace(distribution.Distribution):
    def __init__(self, loc, scale) -> None: ...
    @property
    def mean(self): ...
    @property
    def stddev(self): ...
    @property
    def variance(self): ...
    def log_prob(self, value): ...
    def entropy(self): ...
    def cdf(self, value): ...
    def icdf(self, value): ...
    def sample(self, shape=()): ...
    def rsample(self, shape): ...
    def kl_divergence(self, other): ...
