from _typeshed import Incomplete
from paddle.distribution.normal import Normal as Normal
from paddle.distribution.transform import ExpTransform as ExpTransform
from paddle.distribution.transformed_distribution import TransformedDistribution as TransformedDistribution

class LogNormal(TransformedDistribution):
    loc: Incomplete
    scale: Incomplete
    def __init__(self, loc, scale) -> None: ...
    @property
    def mean(self): ...
    @property
    def variance(self): ...
    def entropy(self): ...
    def probs(self, value): ...
    def kl_divergence(self, other): ...
