from paddle.distribution import distribution as distribution, independent as independent, transform as transform

class TransformedDistribution(distribution.Distribution):
    def __init__(self, base, transforms) -> None: ...
    def sample(self, shape=()): ...
    def rsample(self, shape=()): ...
    def log_prob(self, value): ...
