from ...compiler import CompiledProgram as CompiledProgram
from _typeshed import Incomplete

class SerializableBase:
    def serialize(self, path) -> None: ...
    def deserialize(self, path) -> None: ...

class PaddleModel(SerializableBase):
    def __init__(self, exe, program) -> None: ...
    def serialize(self, path) -> None: ...
    def deserialize(self, path) -> None: ...

class CheckpointSaver:
    def __init__(self, fs) -> None: ...
    def save_checkpoint(self, path, slists, trainer_id: Incomplete | None = None, local_cache_path: str = '.cache'): ...
    def load_checkpoint(self, path, slists, trainer_id, local_cache_path: str = '.cache', checkpoint_no: Incomplete | None = None, ignore_empty: bool = True): ...
    def get_checkpoint_no(self, root_path): ...
    def clean_redundant_checkpoints(self, root_path, reserved=[]) -> None: ...
