from _typeshed import Incomplete
from paddle.base.log_helper import get_logger as get_logger

class OperatorStatsUnit:
    op_type: Incomplete
    fp32_calls: int
    fp16_calls: int
    bf16_calls: int
    other_calls: int
    def __init__(self) -> None: ...
    def update(self, dtype) -> None: ...
    def addto(self, another) -> None: ...
    def convert_to_list(self): ...

def collect_operator_stats(program: Incomplete | None = None, print_subblocks: bool = False): ...
