from _typeshed import Incomplete
from enum import Enum
from paddle.base.log_helper import get_logger as get_logger

class FunctionType(Enum):
    FP16_ONLY = 0
    COMMON = 1

class Function:
    fn: Incomplete
    def __init__(self, fn) -> None: ...
    def __call__(self, *args, **kwargs): ...

class Namespace:
    function_map: Incomplete
    def __init__(self) -> None: ...
    @staticmethod
    def get_instance(): ...
    def register(self, fn, key): ...
    def get(self, *args, **kwargs): ...

def overload(key): ...
