from .meta_optimizer_base import MetaOptimizerBase as MetaOptimizerBase
from _typeshed import Incomplete
from paddle.incubate.optimizer import LarsMomentumOptimizer as LarsMomentumOptimizer
from paddle.optimizer import Momentum as Momentum

class LarsOptimizer(MetaOptimizerBase):
    inner_opt: Incomplete
    lars_opt: Incomplete
    meta_optimizers_white_list: Incomplete
    meta_optimizers_black_list: Incomplete
    def __init__(self, optimizer) -> None: ...
    def backward(self, loss, startup_program: Incomplete | None = None, parameter_list: Incomplete | None = None, no_grad_set: Incomplete | None = None, callbacks: Incomplete | None = None): ...
    def apply_gradients(self, params_grads): ...
    def apply_optimize(self, loss, startup_program, params_grads): ...
    def minimize_impl(self, loss, startup_program: Incomplete | None = None, parameter_list: Incomplete | None = None, no_grad_set: Incomplete | None = None): ...
