from _typeshed import Incomplete
from paddle.base import core as core, framework as framework

name_mapping: Incomplete
core_ops_args_info: Incomplete
core_ops_args_type_info: Incomplete
core_ops_returns_info: Incomplete

class Tracer(core.Tracer):
    def __init__(self) -> None: ...
    def eager_legacy_trace_op(self, op_type, inputs, outputs, attrs, stop_gradient: bool = False, inplace_map: Incomplete | None = None) -> None: ...
    def eager_trace_op(self, op_type, inputs, outputs, attrs, stop_gradient: bool = False, inplace_map: Incomplete | None = None) -> None: ...
    def trace_op(self, type, inputs, outputs, attrs, stop_gradient: bool = False, inplace_map: Incomplete | None = None) -> None: ...
    def train_mode(self) -> None: ...
    def eval_mode(self) -> None: ...
