__all__ = ['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'abs_', 'accuracy', 'acos', 'acos_', 'acosh', 'acosh_', 'adadelta', 'adagrad', 'adam', 'adamax', 'adamw', 'add_act_xpu', 'add_layernorm_xpu', 'add_position_encoding', 'addcmul_xpu', 'addmm', 'addmm_', 'affine_channel', 'affine_channel_', 'affine_grid', 'all_gather', 'all_reduce', 'all_to_all', 'allclose', 'alloc_float_status', 'anchor_generator', 'angle', 'arg_max', 'arg_min', 'argsort', 'as_complex', 'as_real', 'as_strided', 'asin', 'asin_', 'asinh', 'asinh_', 'assert', 'assign', 'assign_pos', 'assign_value', 'atan', 'atan2', 'atan_', 'atanh', 'atanh_', 'attention_lstm', 'auc', 'average_accumulates', 'batch_fc', 'batch_norm', 'bce_loss', 'bce_loss_', 'beam_search', 'beam_search_decode', 'bernoulli', 'bicubic_interp', 'bicubic_interp_v2', 'bilateral_slice', 'bilinear_interp', 'bilinear_interp_v2', 'bilinear_tensor_product', 'bincount', 'bipartite_match', 'bitwise_and', 'bitwise_and_', 'bitwise_not', 'bitwise_not_', 'bitwise_or', 'bitwise_or_', 'bitwise_xor', 'bitwise_xor_', 'block_multihead_attention', 'bmm', 'bn_act_xpu', 'box_clip', 'box_coder', 'box_decoder_and_assign', 'bpr_loss', 'brelu', 'brelu_', 'broadcast', 'broadcast_tensors', 'cast', 'ceil', 'ceil_', 'celu', 'channel_shuffle', 'check_finite_and_unscale', 'check_finite_and_unscale_', 'check_memory_continue', 'check_numerics', 'cholesky', 'cholesky_solve', 'chunk_eval', 'class_center_sample', 'clear_float_status', 'clip', 'clip_', 'clip_by_norm', 'coalesce_tensor', 'collect_fpn_proposals', 'complex', 'concat', 'conj', 'conv1d_xpu', 'conv2d', 'conv2d_transpose', 'conv2d_transpose_xpu', 'conv2d_xpu', 'conv3d', 'conv3d_transpose', 'correlation', 'cos', 'cos_', 'cosh', 'cosh_', 'crf_decoding', 'crop', 'crop_tensor', 'cross', 'cross_entropy', 'cross_entropy2', 'ctc_align', 'cudnn_lstm', 'cummax', 'cummin', 'cumprod', 'cumprod_', 'cumsum', 'cumsum_', 'cvm', 'data', 'data_norm', 'decayed_adagrad', 'decode_jpeg', 'deformable_conv', 'deformable_conv_v1', 'deformable_psroi_pooling', 'density_prior_box', 'depthwise_conv2d', 'depthwise_conv2d_transpose', 'dequantize', 'dequantize_abs_max', 'dequantize_linear', 'dequantize_log', 'dequantize_xpu', 'detection_map', 'determinant', 'dgc_clip_by_norm', 'dgc_momentum', 'diag_embed', 'diag_v2', 'diagonal', 'digamma', 'digamma_', 'dirichlet', 'dist', 'dist_concat', 'distribute_fpn_proposals', 'distributed_fused_lamb', 'distributed_fused_lamb_init', 'dot', 'dpsgd', 'dropout', 'dropout_nd', 'edit_distance', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'einsum', 'elementwise_add', 'elementwise_add_', 'elementwise_div', 'elementwise_floordiv', 'elementwise_fmax', 'elementwise_fmin', 'elementwise_heaviside', 'elementwise_max', 'elementwise_min', 'elementwise_mod', 'elementwise_mod_', 'elementwise_mul', 'elementwise_pow', 'elementwise_sub', 'elementwise_sub_', 'elu', 'elu_', 'embedding_with_eltwise_add_xpu', 'empty', 'equal', 'equal_all', 'erf', 'erf_', 'erfinv', 'erfinv_', 'exp', 'exp_', 'expand', 'expand_as_v2', 'expand_v2', 'expm1', 'expm1_', 'exponential', 'exponential_', 'eye', 'fake_channel_wise_dequantize_max_abs', 'fake_channel_wise_quantize_abs_max', 'fake_channel_wise_quantize_dequantize_abs_max', 'fake_dequantize_max_abs', 'fake_quantize_abs_max', 'fake_quantize_dequantize_abs_max', 'fake_quantize_dequantize_moving_average_abs_max', 'fake_quantize_moving_average_abs_max', 'fake_quantize_range_abs_max', 'fast_layernorm_xpu', 'fast_where_xpu', 'faster_tokenizer', 'fc', 'fc_xpu', 'feed', 'fetch', 'fetch_v2', 'fft_c2c', 'fft_c2r', 'fft_r2c', 'fill_any', 'fill_any_', 'fill_any_like', 'fill_constant', 'fill_constant_batch_size_like', 'fill_diagonal', 'fill_diagonal_', 'fill_diagonal_tensor', 'fill_diagonal_tensor_', 'fill_zeros_like', 'fill_zeros_like2', 'flash_attn', 'flash_attn_unpadded', 'flatten2', 'flatten2_', 'flatten_contiguous_range', 'flatten_contiguous_range_', 'flip', 'floor', 'floor_', 'fold', 'frame', 'frobenius_norm', 'fsp', 'ftrl', 'full_int_array', 'fused_adam', 'fused_bias_act', 'fused_bias_dropout_residual_layer_norm', 'fused_bias_residual_layernorm', 'fused_conv2d', 'fused_conv2d_add_act', 'fused_conv3d', 'fused_dconv_drelu_dbn', 'fused_dropout_add', 'fused_elementwise_add', 'fused_elementwise_div', 'fused_elementwise_mul', 'fused_elementwise_sub', 'fused_elemwise_activation', 'fused_elemwise_add_activation', 'fused_embedding_eltwise_layernorm', 'fused_embedding_fc_lstm', 'fused_embedding_seq_pool', 'fused_fc_elementwise_layernorm', 'fused_linear_param_grad_add', 'fused_matmul', 'fused_multi_transformer_int8_xpu', 'fused_multi_transformer_xpu', 'fused_rotary_position_embedding', 'fused_scale_bias_add_relu', 'fused_scale_bias_relu_conv_bn', 'fused_seqpool_cvm', 'fused_softmax_mask', 'fused_softmax_mask_upper_triangle', 'fused_softplus', 'fused_transpose', 'fusion_gru', 'fusion_lstm', 'fusion_repeated_fc_relu', 'fusion_seqconv_eltadd_relu', 'fusion_seqexpand_concat_fc', 'fusion_seqpool_concat', 'fusion_seqpool_cvm_concat', 'fusion_squared_mat_sub', 'fusion_transpose_flatten_concat', 'gather', 'gather_nd', 'gather_tree', 'gaussian_inplace', 'gaussian_inplace_', 'gaussian_random', 'gelu', 'generate_mask_labels', 'generate_proposal_labels', 'generate_proposals', 'generate_proposals_v2', 'generate_sequence_xpu', 'get_core_ops_args_info', 'get_core_ops_args_type_info', 'get_core_ops_returns_info', 'get_float_status', 'get_tensor_from_selected_rows', 'grad_add', 'graph_khop_sampler', 'graph_reindex', 'graph_sample_neighbors', 'graph_send_recv', 'graph_send_ue_recv', 'graph_send_uv', 'greater_equal', 'greater_than', 'grid_sampler', 'group_norm', 'gru', 'gru_unit', 'gumbel_softmax', 'hard_shrink', 'hard_sigmoid', 'hard_swish', 'hash', 'hierarchical_sigmoid', 'hinge_loss', 'histogram', 'huber_loss', 'i0', 'i0_', 'i0e', 'i1', 'i1e', 'identity_loss', 'identity_loss_', 'im2sequence', 'imag', 'increment', 'index_add', 'index_add_', 'index_put', 'index_put_', 'index_sample', 'index_select', 'index_select_strided', 'instance_norm', 'inverse', 'iou_similarity', 'is_empty', 'isclose', 'isfinite_v2', 'isinf', 'isinf_v2', 'isnan', 'isnan_v2', 'kldiv_loss', 'kron', 'kthvalue', 'l1_norm', 'label_smooth', 'lamb', 'lars_momentum', 'layer_norm', 'layer_norm_act_xpu', 'leaky_relu', 'leaky_relu_', 'lerp', 'lerp_', 'less_equal', 'less_than', 'lgamma', 'lgamma_', 'limit_by_capacity', 'linear_chain_crf', 'linear_interp', 'linear_interp_v2', 'linspace', 'llm_int8_linear', 'load', 'load_combine', 'locality_aware_nms', 'lod_reset', 'lod_reset_', 'log', 'log10', 'log10_', 'log1p', 'log1p_', 'log2', 'log2_', 'log_', 'log_loss', 'log_softmax', 'logcumsumexp', 'logical_and', 'logical_and_', 'logical_not', 'logical_not_', 'logical_or', 'logical_or_', 'logical_xor', 'logical_xor_', 'logit', 'logit_', 'logsigmoid', 'logspace', 'logsumexp', 'lookup_table', 'lookup_table_dequant', 'lookup_table_v2', 'lrn', 'lstm', 'lstsq', 'lu', 'lu_', 'lu_unpack', 'margin_cross_entropy', 'masked_multihead_attention', 'masked_select', 'matmul', 'matmul_v2', 'matrix_nms', 'matrix_power', 'matrix_rank', 'max_pool2d_with_index', 'max_pool3d_with_index', 'maxout', 'mean', 'memcpy', 'memcpy_d2h', 'memcpy_h2d', 'memory_efficient_attention', 'merge_selected_rows', 'merged_adam', 'merged_momentum', 'meshgrid', 'mine_hard_examples', 'minus', 'mish', 'mode', 'modified_huber_loss', 'momentum', 'moving_average_abs_max_scale', 'mul', 'multi_dot', 'multi_encoder_xpu', 'multiclass_nms', 'multiclass_nms2', 'multiclass_nms3', 'multihead_matmul', 'multinomial', 'multiplex', 'mv', 'nanmedian', 'nce', 'nearest_interp', 'nearest_interp_v2', 'nextafter', 'nll_loss', 'nms', 'nop', 'norm', 'not_equal', 'npu_identity', 'number_count', 'one_hot_v2', 'overlap_add', 'p_norm', 'p_recv', 'p_recv_array', 'p_send', 'p_send_array', 'pad', 'pad3d', 'partial_concat', 'partial_sum', 'pir_run_program', 'pixel_shuffle', 'pixel_unshuffle', 'poisson', 'polygamma', 'polygamma_', 'polygon_box_transform', 'pool2d', 'pool3d', 'positive_negative_pair', 'pow', 'pow2_decay_with_linear_warmup', 'pow_', 'precision_recall', 'prelu', 'prior_box', 'proximal_gd', 'prune_gate_by_capacity', 'psroi_pool', 'pull_box_extended_sparse', 'pull_box_sparse', 'pull_gpups_sparse', 'pull_sparse', 'pull_sparse_v2', 'push_dense', 'put_along_axis', 'put_along_axis_', 'pyramid_hash', 'qr', 'quant_linear', 'quantize_linear', 'quantize_xpu', 'randint', 'random_routing', 'random_routing_', 'randperm', 'range', 'rank_attention', 'rank_loss', 'read_file', 'real', 'reciprocal', 'reciprocal_', 'reduce', 'reduce_all', 'reduce_amax', 'reduce_amin', 'reduce_any', 'reduce_max', 'reduce_mean', 'reduce_min', 'reduce_prod', 'reduce_scatter', 'reduce_sum', 'relu', 'relu6', 'relu_', 'renorm', 'renorm_', 'repeat_interleave', 'reshape', 'reshape2', 'reshape2_', 'reshape_', 'retinanet_detection_output', 'retinanet_target_assign', 'reverse', 'rms_norm', 'rmsprop', 'rnn', 'roi_align', 'roi_pool', 'roll', 'round', 'round_', 'row_conv', 'rpn_target_assign', 'rrelu', 'rsqrt', 'rsqrt_', 'run_program', 'sampling_id', 'save', 'save_combine', 'scale', 'scale_', 'scatter', 'scatter_', 'scatter_nd_add', 'searchsorted', 'seed', 'segment_pool', 'self_dp_attention', 'selu', 'sequence_concat', 'sequence_conv', 'sequence_enumerate', 'sequence_erase', 'sequence_expand', 'sequence_expand_as', 'sequence_mask', 'sequence_pad', 'sequence_pool', 'sequence_reshape', 'sequence_reverse', 'sequence_scatter', 'sequence_slice', 'sequence_softmax', 'sequence_unpad', 'set_value', 'set_value_', 'sgd', 'shadow_output', 'shape', 'shard_index', 'share_buffer', 'share_data', 'shuffle_batch', 'shuffle_channel', 'sigmoid', 'sigmoid_', 'sigmoid_cross_entropy_with_logits', 'sigmoid_cross_entropy_with_logits_', 'sign', 'silu', 'similarity_focus', 'sin', 'sin_', 'sinh', 'sinh_', 'size', 'skip_layernorm', 'slice', 'slogdeterminant', 'soft_relu', 'soft_relu_', 'softmax', 'softmax_', 'softmax_with_cross_entropy', 'softmax_with_cross_entropy_', 'softplus', 'softshrink', 'softsign', 'solve', 'sparse_momentum', 'spectral_norm', 'split', 'spp', 'sqrt', 'sqrt_', 'square', 'squared_l2_norm', 'squeeze2', 'squeeze2_', 'squeeze_excitation_block', 'stack', 'stanh', 'stft', 'strided_slice', 'sum', 'svd', 'swish', 'take_along_axis', 'tan', 'tan_', 'tanh', 'tanh_', 'tanh_shrink', 'tdm_child', 'tdm_sampler', 'teacher_student_sigmoid_loss', 'temporal_shift', 'tensor_unfold', 'thresholded_relu', 'thresholded_relu_', 'tile', 'top_k', 'top_k_v2', 'top_p_sampling', 'trace', 'transfer_dtype', 'transfer_layout', 'transpose', 'transpose2', 'triangular_solve', 'tril_indices', 'tril_triu', 'trilinear_interp', 'trilinear_interp_v2', 'triu_indices', 'trunc', 'trunc_', 'truncated_gaussian_random', 'unbind', 'unfold', 'uniform_random', 'uniform_random_batch_size_like', 'uniform_random_inplace', 'uniform_random_inplace_', 'unique', 'unique_consecutive', 'unique_with_counts', 'unpool', 'unpool3d', 'unsqueeze2', 'unsqueeze2_', 'unstack', 'unzip', 'update_loss_scaling', 'variable_length_memory_efficient_attention', 'view_dtype', 'view_shape', 'viterbi_decode', 'warpctc', 'warprnnt', 'weight_dequantize', 'weight_only_linear', 'weight_quantize', 'weighted_sample_neighbors', 'where', 'where_', 'where_index', 'yolo_box', 'yolo_box_xpu', 'yolov3_loss']

# Names in __all__ with no definition:
#   __doc__
#   __loader__
#   __name__
#   __package__
#   __spec__
#   abs
#   abs_
#   accuracy
#   acos
#   acos_
#   acosh
#   acosh_
#   adadelta
#   adagrad
#   adam
#   adamax
#   adamw
#   add_act_xpu
#   add_layernorm_xpu
#   add_position_encoding
#   addcmul_xpu
#   addmm
#   addmm_
#   affine_channel
#   affine_channel_
#   affine_grid
#   all_gather
#   all_reduce
#   all_to_all
#   allclose
#   alloc_float_status
#   anchor_generator
#   angle
#   arg_max
#   arg_min
#   argsort
#   as_complex
#   as_real
#   as_strided
#   asin
#   asin_
#   asinh
#   asinh_
#   assert
#   assign
#   assign_pos
#   assign_value
#   atan
#   atan2
#   atan_
#   atanh
#   atanh_
#   attention_lstm
#   auc
#   average_accumulates
#   batch_fc
#   batch_norm
#   bce_loss
#   bce_loss_
#   beam_search
#   beam_search_decode
#   bernoulli
#   bicubic_interp
#   bicubic_interp_v2
#   bilateral_slice
#   bilinear_interp
#   bilinear_interp_v2
#   bilinear_tensor_product
#   bincount
#   bipartite_match
#   bitwise_and
#   bitwise_and_
#   bitwise_not
#   bitwise_not_
#   bitwise_or
#   bitwise_or_
#   bitwise_xor
#   bitwise_xor_
#   block_multihead_attention
#   bmm
#   bn_act_xpu
#   box_clip
#   box_coder
#   box_decoder_and_assign
#   bpr_loss
#   brelu
#   brelu_
#   broadcast
#   broadcast_tensors
#   cast
#   ceil
#   ceil_
#   celu
#   channel_shuffle
#   check_finite_and_unscale
#   check_finite_and_unscale_
#   check_memory_continue
#   check_numerics
#   cholesky
#   cholesky_solve
#   chunk_eval
#   class_center_sample
#   clear_float_status
#   clip
#   clip_
#   clip_by_norm
#   coalesce_tensor
#   collect_fpn_proposals
#   complex
#   concat
#   conj
#   conv1d_xpu
#   conv2d
#   conv2d_transpose
#   conv2d_transpose_xpu
#   conv2d_xpu
#   conv3d
#   conv3d_transpose
#   correlation
#   cos
#   cos_
#   cosh
#   cosh_
#   crf_decoding
#   crop
#   crop_tensor
#   cross
#   cross_entropy
#   cross_entropy2
#   ctc_align
#   cudnn_lstm
#   cummax
#   cummin
#   cumprod
#   cumprod_
#   cumsum
#   cumsum_
#   cvm
#   data
#   data_norm
#   decayed_adagrad
#   decode_jpeg
#   deformable_conv
#   deformable_conv_v1
#   deformable_psroi_pooling
#   density_prior_box
#   depthwise_conv2d
#   depthwise_conv2d_transpose
#   dequantize
#   dequantize_abs_max
#   dequantize_linear
#   dequantize_log
#   dequantize_xpu
#   detection_map
#   determinant
#   dgc_clip_by_norm
#   dgc_momentum
#   diag_embed
#   diag_v2
#   diagonal
#   digamma
#   digamma_
#   dirichlet
#   dist
#   dist_concat
#   distribute_fpn_proposals
#   distributed_fused_lamb
#   distributed_fused_lamb_init
#   dot
#   dpsgd
#   dropout
#   dropout_nd
#   edit_distance
#   eig
#   eigh
#   eigvals
#   eigvalsh
#   einsum
#   elementwise_add
#   elementwise_add_
#   elementwise_div
#   elementwise_floordiv
#   elementwise_fmax
#   elementwise_fmin
#   elementwise_heaviside
#   elementwise_max
#   elementwise_min
#   elementwise_mod
#   elementwise_mod_
#   elementwise_mul
#   elementwise_pow
#   elementwise_sub
#   elementwise_sub_
#   elu
#   elu_
#   embedding_with_eltwise_add_xpu
#   empty
#   equal
#   equal_all
#   erf
#   erf_
#   erfinv
#   erfinv_
#   exp
#   exp_
#   expand
#   expand_as_v2
#   expand_v2
#   expm1
#   expm1_
#   exponential
#   exponential_
#   eye
#   fake_channel_wise_dequantize_max_abs
#   fake_channel_wise_quantize_abs_max
#   fake_channel_wise_quantize_dequantize_abs_max
#   fake_dequantize_max_abs
#   fake_quantize_abs_max
#   fake_quantize_dequantize_abs_max
#   fake_quantize_dequantize_moving_average_abs_max
#   fake_quantize_moving_average_abs_max
#   fake_quantize_range_abs_max
#   fast_layernorm_xpu
#   fast_where_xpu
#   faster_tokenizer
#   fc
#   fc_xpu
#   feed
#   fetch
#   fetch_v2
#   fft_c2c
#   fft_c2r
#   fft_r2c
#   fill_any
#   fill_any_
#   fill_any_like
#   fill_constant
#   fill_constant_batch_size_like
#   fill_diagonal
#   fill_diagonal_
#   fill_diagonal_tensor
#   fill_diagonal_tensor_
#   fill_zeros_like
#   fill_zeros_like2
#   flash_attn
#   flash_attn_unpadded
#   flatten2
#   flatten2_
#   flatten_contiguous_range
#   flatten_contiguous_range_
#   flip
#   floor
#   floor_
#   fold
#   frame
#   frobenius_norm
#   fsp
#   ftrl
#   full_int_array
#   fused_adam
#   fused_bias_act
#   fused_bias_dropout_residual_layer_norm
#   fused_bias_residual_layernorm
#   fused_conv2d
#   fused_conv2d_add_act
#   fused_conv3d
#   fused_dconv_drelu_dbn
#   fused_dropout_add
#   fused_elementwise_add
#   fused_elementwise_div
#   fused_elementwise_mul
#   fused_elementwise_sub
#   fused_elemwise_activation
#   fused_elemwise_add_activation
#   fused_embedding_eltwise_layernorm
#   fused_embedding_fc_lstm
#   fused_embedding_seq_pool
#   fused_fc_elementwise_layernorm
#   fused_linear_param_grad_add
#   fused_matmul
#   fused_multi_transformer_int8_xpu
#   fused_multi_transformer_xpu
#   fused_rotary_position_embedding
#   fused_scale_bias_add_relu
#   fused_scale_bias_relu_conv_bn
#   fused_seqpool_cvm
#   fused_softmax_mask
#   fused_softmax_mask_upper_triangle
#   fused_softplus
#   fused_transpose
#   fusion_gru
#   fusion_lstm
#   fusion_repeated_fc_relu
#   fusion_seqconv_eltadd_relu
#   fusion_seqexpand_concat_fc
#   fusion_seqpool_concat
#   fusion_seqpool_cvm_concat
#   fusion_squared_mat_sub
#   fusion_transpose_flatten_concat
#   gather
#   gather_nd
#   gather_tree
#   gaussian_inplace
#   gaussian_inplace_
#   gaussian_random
#   gelu
#   generate_mask_labels
#   generate_proposal_labels
#   generate_proposals
#   generate_proposals_v2
#   generate_sequence_xpu
#   get_core_ops_args_info
#   get_core_ops_args_type_info
#   get_core_ops_returns_info
#   get_float_status
#   get_tensor_from_selected_rows
#   grad_add
#   graph_khop_sampler
#   graph_reindex
#   graph_sample_neighbors
#   graph_send_recv
#   graph_send_ue_recv
#   graph_send_uv
#   greater_equal
#   greater_than
#   grid_sampler
#   group_norm
#   gru
#   gru_unit
#   gumbel_softmax
#   hard_shrink
#   hard_sigmoid
#   hard_swish
#   hash
#   hierarchical_sigmoid
#   hinge_loss
#   histogram
#   huber_loss
#   i0
#   i0_
#   i0e
#   i1
#   i1e
#   identity_loss
#   identity_loss_
#   im2sequence
#   imag
#   increment
#   index_add
#   index_add_
#   index_put
#   index_put_
#   index_sample
#   index_select
#   index_select_strided
#   instance_norm
#   inverse
#   iou_similarity
#   is_empty
#   isclose
#   isfinite_v2
#   isinf
#   isinf_v2
#   isnan
#   isnan_v2
#   kldiv_loss
#   kron
#   kthvalue
#   l1_norm
#   label_smooth
#   lamb
#   lars_momentum
#   layer_norm
#   layer_norm_act_xpu
#   leaky_relu
#   leaky_relu_
#   lerp
#   lerp_
#   less_equal
#   less_than
#   lgamma
#   lgamma_
#   limit_by_capacity
#   linear_chain_crf
#   linear_interp
#   linear_interp_v2
#   linspace
#   llm_int8_linear
#   load
#   load_combine
#   locality_aware_nms
#   lod_reset
#   lod_reset_
#   log
#   log10
#   log10_
#   log1p
#   log1p_
#   log2
#   log2_
#   log_
#   log_loss
#   log_softmax
#   logcumsumexp
#   logical_and
#   logical_and_
#   logical_not
#   logical_not_
#   logical_or
#   logical_or_
#   logical_xor
#   logical_xor_
#   logit
#   logit_
#   logsigmoid
#   logspace
#   logsumexp
#   lookup_table
#   lookup_table_dequant
#   lookup_table_v2
#   lrn
#   lstm
#   lstsq
#   lu
#   lu_
#   lu_unpack
#   margin_cross_entropy
#   masked_multihead_attention
#   masked_select
#   matmul
#   matmul_v2
#   matrix_nms
#   matrix_power
#   matrix_rank
#   max_pool2d_with_index
#   max_pool3d_with_index
#   maxout
#   mean
#   memcpy
#   memcpy_d2h
#   memcpy_h2d
#   memory_efficient_attention
#   merge_selected_rows
#   merged_adam
#   merged_momentum
#   meshgrid
#   mine_hard_examples
#   minus
#   mish
#   mode
#   modified_huber_loss
#   momentum
#   moving_average_abs_max_scale
#   mul
#   multi_dot
#   multi_encoder_xpu
#   multiclass_nms
#   multiclass_nms2
#   multiclass_nms3
#   multihead_matmul
#   multinomial
#   multiplex
#   mv
#   nanmedian
#   nce
#   nearest_interp
#   nearest_interp_v2
#   nextafter
#   nll_loss
#   nms
#   nop
#   norm
#   not_equal
#   npu_identity
#   number_count
#   one_hot_v2
#   overlap_add
#   p_norm
#   p_recv
#   p_recv_array
#   p_send
#   p_send_array
#   pad
#   pad3d
#   partial_concat
#   partial_sum
#   pir_run_program
#   pixel_shuffle
#   pixel_unshuffle
#   poisson
#   polygamma
#   polygamma_
#   polygon_box_transform
#   pool2d
#   pool3d
#   positive_negative_pair
#   pow
#   pow2_decay_with_linear_warmup
#   pow_
#   precision_recall
#   prelu
#   prior_box
#   proximal_gd
#   prune_gate_by_capacity
#   psroi_pool
#   pull_box_extended_sparse
#   pull_box_sparse
#   pull_gpups_sparse
#   pull_sparse
#   pull_sparse_v2
#   push_dense
#   put_along_axis
#   put_along_axis_
#   pyramid_hash
#   qr
#   quant_linear
#   quantize_linear
#   quantize_xpu
#   randint
#   random_routing
#   random_routing_
#   randperm
#   range
#   rank_attention
#   rank_loss
#   read_file
#   real
#   reciprocal
#   reciprocal_
#   reduce
#   reduce_all
#   reduce_amax
#   reduce_amin
#   reduce_any
#   reduce_max
#   reduce_mean
#   reduce_min
#   reduce_prod
#   reduce_scatter
#   reduce_sum
#   relu
#   relu6
#   relu_
#   renorm
#   renorm_
#   repeat_interleave
#   reshape
#   reshape2
#   reshape2_
#   reshape_
#   retinanet_detection_output
#   retinanet_target_assign
#   reverse
#   rms_norm
#   rmsprop
#   rnn
#   roi_align
#   roi_pool
#   roll
#   round
#   round_
#   row_conv
#   rpn_target_assign
#   rrelu
#   rsqrt
#   rsqrt_
#   run_program
#   sampling_id
#   save
#   save_combine
#   scale
#   scale_
#   scatter
#   scatter_
#   scatter_nd_add
#   searchsorted
#   seed
#   segment_pool
#   self_dp_attention
#   selu
#   sequence_concat
#   sequence_conv
#   sequence_enumerate
#   sequence_erase
#   sequence_expand
#   sequence_expand_as
#   sequence_mask
#   sequence_pad
#   sequence_pool
#   sequence_reshape
#   sequence_reverse
#   sequence_scatter
#   sequence_slice
#   sequence_softmax
#   sequence_unpad
#   set_value
#   set_value_
#   sgd
#   shadow_output
#   shape
#   shard_index
#   share_buffer
#   share_data
#   shuffle_batch
#   shuffle_channel
#   sigmoid
#   sigmoid_
#   sigmoid_cross_entropy_with_logits
#   sigmoid_cross_entropy_with_logits_
#   sign
#   silu
#   similarity_focus
#   sin
#   sin_
#   sinh
#   sinh_
#   size
#   skip_layernorm
#   slice
#   slogdeterminant
#   soft_relu
#   soft_relu_
#   softmax
#   softmax_
#   softmax_with_cross_entropy
#   softmax_with_cross_entropy_
#   softplus
#   softshrink
#   softsign
#   solve
#   sparse_momentum
#   spectral_norm
#   split
#   spp
#   sqrt
#   sqrt_
#   square
#   squared_l2_norm
#   squeeze2
#   squeeze2_
#   squeeze_excitation_block
#   stack
#   stanh
#   stft
#   strided_slice
#   sum
#   svd
#   swish
#   take_along_axis
#   tan
#   tan_
#   tanh
#   tanh_
#   tanh_shrink
#   tdm_child
#   tdm_sampler
#   teacher_student_sigmoid_loss
#   temporal_shift
#   tensor_unfold
#   thresholded_relu
#   thresholded_relu_
#   tile
#   top_k
#   top_k_v2
#   top_p_sampling
#   trace
#   transfer_dtype
#   transfer_layout
#   transpose
#   transpose2
#   triangular_solve
#   tril_indices
#   tril_triu
#   trilinear_interp
#   trilinear_interp_v2
#   triu_indices
#   trunc
#   trunc_
#   truncated_gaussian_random
#   unbind
#   unfold
#   uniform_random
#   uniform_random_batch_size_like
#   uniform_random_inplace
#   uniform_random_inplace_
#   unique
#   unique_consecutive
#   unique_with_counts
#   unpool
#   unpool3d
#   unsqueeze2
#   unsqueeze2_
#   unstack
#   unzip
#   update_loss_scaling
#   variable_length_memory_efficient_attention
#   view_dtype
#   view_shape
#   viterbi_decode
#   warpctc
#   warprnnt
#   weight_dequantize
#   weight_only_linear
#   weight_quantize
#   weighted_sample_neighbors
#   where
#   where_
#   where_index
#   yolo_box
#   yolo_box_xpu
#   yolov3_loss
