from _typeshed import Incomplete

__all__ = ['fft', 'ifft', 'rfft', 'irfft', 'hfft', 'ihfft', 'fft2', 'ifft2', 'rfft2', 'irfft2', 'hfft2', 'ihfft2', 'fftn', 'ifftn', 'rfftn', 'irfftn', 'hfftn', 'ihfftn', 'fftfreq', 'rfftfreq', 'fftshift', 'ifftshift']

def fft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def ifft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def rfft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def irfft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def hfft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def ihfft(x, n: Incomplete | None = None, axis: int = -1, norm: str = 'backward', name: Incomplete | None = None): ...
def fftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def ifftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def rfftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def irfftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def hfftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def ihfftn(x, s: Incomplete | None = None, axes: Incomplete | None = None, norm: str = 'backward', name: Incomplete | None = None): ...
def fft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def ifft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def rfft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def irfft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def hfft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def ihfft2(x, s: Incomplete | None = None, axes=(-2, -1), norm: str = 'backward', name: Incomplete | None = None): ...
def fftfreq(n, d: float = 1.0, dtype: Incomplete | None = None, name: Incomplete | None = None): ...
def rfftfreq(n, d: float = 1.0, dtype: Incomplete | None = None, name: Incomplete | None = None): ...
def fftshift(x, axes: Incomplete | None = None, name: Incomplete | None = None): ...
def ifftshift(x, axes: Incomplete | None = None, name: Incomplete | None = None): ...
