__all__ = ['L1Decay', 'L2Decay']

class WeightDecayRegularizer:
    def __init__(self) -> None: ...
    def __call__(self, param, grad, block) -> None: ...

class L1Decay(WeightDecayRegularizer):
    def __init__(self, coeff: float = 0.0) -> None: ...
    def __call__(self, param, grad, block): ...

class L2Decay(WeightDecayRegularizer):
    def __init__(self, coeff: float = 0.0) -> None: ...
    def __call__(self, param, grad, block): ...
