from paddle.base.data_feeder import check_type as check_type
from paddle.base.framework import Variable as Variable

def check_input_type(input, name, op_name) -> None: ...
def check_initial_inverse_hessian_estimate(H0): ...
