from _typeshed import Incomplete
from paddle.utils import try_import as try_import

def set_image_backend(backend) -> None: ...
def get_image_backend(): ...
def image_load(path, backend: Incomplete | None = None): ...
