from .log_util import logger as logger
from _typeshed import Incomplete
from paddle import framework as framework
from paddle.base import core as core
from paddle.distributed.parallel import build_groups as build_groups, in_dynamic_mode as in_dynamic_mode, sync_params_buffers as sync_params_buffers

def obtain_optimizer_parameters_list(optimizer): ...
def broadcast_input_data(hcg, *inputs, **kwargs): ...
def broadcast_mp_parameters(model, hcg) -> None: ...
def broadcast_dp_parameters(model, hcg) -> None: ...
def fused_allreduce_gradients_with_group(parameter_list, group, bucket_size=..., scale: Incomplete | None = None) -> None: ...
def fused_allreduce_gradients(parameter_list, hcg) -> None: ...
def broadcast_sharding_parameters(model, hcg) -> None: ...
def broadcast_sep_parameters(model, hcg) -> None: ...
def unwrap_optimizer(optimizer, optimizer_instances=()): ...
