from _typeshed import Incomplete
from paddle.distributed.utils.log_utils import get_logger as get_logger

logger: Incomplete

def set_log_level(level) -> None: ...
def get_log_level_code(): ...
def get_log_level_name(): ...
def layer_to_str(base, *args, **kwargs): ...
