from _typeshed import Incomplete
from paddle.base import core as core
from paddle.distributed.fleet.meta_optimizers.common import OP_ROLE_KEY as OP_ROLE_KEY
from paddle.static import Parameter as Parameter

logger: Incomplete
formatter: Incomplete
ch: Incomplete

def tensor_parallel_sync_filter_fn(param, pos_emb: bool = True, layer_norm: bool = True, bias: bool = True): ...
def resolute_tensor_parallel_ring_id(program): ...
def copy_parameters(block_, params) -> None: ...
def insert_sync_op(block, idx, tp_degree, sync_mode, sync_ring_id, src_rank, varname, op_role) -> None: ...
def insert_synchronization(block, params_to_sync, tp_degree, sync_ring_id, sync_param, sync_grad, sync_moment, sync_mode, src_rank) -> None: ...
def add_extra_synchronization(program, params_filter_fn=..., tp_degree: int = 8, sync_mode: str = 'broadcast', sync_param: bool = True, sync_grad: bool = False, sync_moment: bool = False, src_rank: int = 0, sync_ring_id: Incomplete | None = None) -> None: ...
