from _typeshed import Incomplete
from paddle.framework import core as core

class HOOK_ACTION:
    ALL_REDUCE: int
    REDUCE: int
    REDUCE_SCATTER: int

alignment: Incomplete
align: Incomplete

def assign_group_by_size(parameters, group_size=...): ...
def flatten_dense_tensors(parameters, use_main_grad: bool = False, fuse_param: bool = True, warp_buffer: bool = False): ...
def bw_hook_func(buffer, param): ...

class ShardingGradView:
    def __init__(self, param, param_buffer, grad_buffer, index, padded_size, sharding_degree, rank, use_main_grad: bool = False) -> None: ...
    def fill_slice_param(self, slice_param) -> None: ...
    def assign_slice_grad(self, slice_param) -> None: ...

def build_reduce_scatter_buffer(parameters, sharding_degree, rank, use_main_grad: bool = False): ...
def get_grad_address(param, use_main_grad): ...

class FusedCommBuffer:
    use_main_grad: Incomplete
    param_storage: Incomplete
    grad_storage: Incomplete
    def __init__(self, id, params, comm_group, acc_steps: int = 1, act: Incomplete | None = None, dst: int = -1, use_main_grad: Incomplete | None = None, fuse_param: bool = False, scale_after_comm: bool = True) -> None: ...
    def add_grad(self, param, use_comm: bool = True) -> None: ...
    def assign_slice_grad(self, param, slice_param) -> None: ...
    def sync_params(self) -> None: ...
    @property
    def params(self): ...
    def comm_grads(self) -> None: ...
    def scale_grads(self) -> None: ...
    def scale_and_split_grads(self) -> None: ...

def obtain_storage(parameters, use_main_grad: bool = False, clip: bool = True, dist: bool = False, fuse_param: bool = True, comm_overlap: bool = False, act: Incomplete | None = None, comm_group: Incomplete | None = None, dst: int = -1, acc_steps: int = 1, scale_after_comm: bool = False): ...
def filter_params(params, is_fp32, is_distributed, need_clip): ...
def fused_parameters(parameters, use_main_grad: bool = False, fuse_param: bool = True, comm_overlap: bool = False, comm_group: Incomplete | None = None, act: Incomplete | None = None, dst: int = -1, acc_step: int = 1, scale_after_comm: bool = False, group_params: bool = False, apply_decay_param_fun: Incomplete | None = None): ...
