from _typeshed import Incomplete

def is_timer_initialized(): ...
def get_timers(): ...
def set_timers() -> None: ...

class _Timer:
    name: Incomplete
    elapsed_: float
    started_: bool
    start_time: Incomplete
    def __init__(self, name) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def reset(self) -> None: ...
    def elapsed(self, reset: bool = True): ...

class Timers:
    timers: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, name): ...
    def log(self, names, normalizer: float = 1.0, reset: bool = True) -> None: ...
