from _typeshed import Incomplete
from paddle.distributed.fleet.meta_optimizers.common import OP_ROLE_KEY as OP_ROLE_KEY, OpRole as OpRole

class GradientClipHelper:
    mp_ring_id: Incomplete
    def __init__(self, mp_ring_id) -> None: ...
    def prune_gradient_clip(self, block, shard, ring_ids) -> None: ...
    def sync_global_norm(self, block, ring_ids, mp_rank) -> None: ...
