from _typeshed import Incomplete

class ProgramDeps:
    def __init__(self, block, start_vars, end_vars) -> None: ...
    def get_sub_block_deps(self, idx): ...
    def get_var_deps(self, var_name): ...
    def crop_input_var_from_op(self, op_idx, var_name) -> None: ...
    def crop_output_var_from_op(self, op_idx, var_name) -> None: ...
    def remove_op(self, op_idx, reserved_vars: Incomplete | None = None) -> None: ...
    def should_remove_op(self, op_idx): ...
