from paddle.distributed.fleet.meta_optimizers.common import OP_ROLE_VAR_KEY as OP_ROLE_VAR_KEY

class WeightDecayHelper:
    def __init__(self) -> None: ...
    def prune_weight_decay(self, block, shard) -> None: ...
