from _typeshed import Incomplete

class ETCDClient:
    retry_times: Incomplete
    client: Incomplete
    def __init__(self, host, port, retry_times: int = 20) -> None: ...
    def put(self, key, value, lease: Incomplete | None = None, prev_kv: bool = False): ...
    def get(self, key): ...
    def delete(self, key, prev_kv: bool = False, return_response: bool = False): ...
    def get_prefix(self, key_prefix, sort_order: Incomplete | None = None, sort_target: str = 'key'): ...
    def delete_prefix(self, prefix): ...
    def lease(self, ttl, lease_id: Incomplete | None = None): ...
    def add_watch_prefix_callback(self, key_prefix, callback, **kwargs): ...
    def cancel_watch(self, watch_id): ...
