from _typeshed import Incomplete

class KVClient:
    endpoint: Incomplete
    def __init__(self, endpoint: str = 'localhost:2379') -> None: ...
    def put(self, key, value): ...
    def get(self, key): ...
    def get_prefix(self, key): ...
    def delete(self, key): ...
    def wait_server_ready(self, timeout: int = 3): ...
