from _typeshed import Incomplete

class Info:
    def json(self): ...
    def dict(self): ...
    def str(self, keys: Incomplete | None = None): ...

def query_smi(query: Incomplete | None = None, query_type: str = 'gpu', index: Incomplete | None = None, dtype: Incomplete | None = None): ...
def query_rocm_smi(query: Incomplete | None = None, index: Incomplete | None = None, dtype: Incomplete | None = None, mem: int = 32150): ...
def get_gpu_info(index: Incomplete | None = None): ...
def get_gpu_util(index: Incomplete | None = None): ...
def get_gpu_process(index: Incomplete | None = None): ...
def has_nvidia_smi(): ...
def has_rocm_smi(): ...
