from _typeshed import Incomplete

LIMIT_LEN_ENVS: Incomplete

class ProcessContext:
    def __init__(self, cmd, env=..., out=..., err=..., group: bool = True, preexec_fn: Incomplete | None = None, shell: bool = False) -> None: ...
    def alive(self): ...
    def exit_code(self): ...
    def start(self) -> None: ...
    def terminate(self, force: bool = False, max_retry: int = 3): ...
    def wait(self, timeout: Incomplete | None = None) -> None: ...
