from paddle.base.core import Partial as Partial, Replicate as Replicate, Shard as Shard

def to_placements(dim_map, mesh, partial_idx=[]): ...
def check_placements_equal(this, that): ...
def to_dim_map(placements, tensor_dims): ...
def get_shard_spec(mesh, placements, tensor_dims): ...
