from ..utils.log_utils import get_logger as get_logger
from .process_mesh import retrive_unique_id_for_process_mesh as retrive_unique_id_for_process_mesh

def is_enable_auto_rand_ctrl(): ...
def enable_auto_rand_ctrl() -> None: ...
def parallel_manual_seed(seed, name: str = '') -> None: ...
def determinate_rng(rank, dims_mapping, process_mesh): ...
def init_auto_parallel_rng() -> None: ...
