from _typeshed import Incomplete
from paddle.incubate.passes import ir as ir

def set_resnet_unit_attrs(resnet_unit, has_shortcut) -> None: ...
def set_resnet_unit_outputs(resnet_unit, meanX, varX, meanZ: Incomplete | None = None, varZ: Incomplete | None = None) -> None: ...
def fuse_resnet_unit(): ...
