from .ast3 import ast_to_gast as ast_to_gast, gast_to_ast as gast_to_ast
from _typeshed import Incomplete
from ast import AST

class TypeIgnore(AST): ...

py_version: Incomplete

def parse(*args, **kwargs): ...
def literal_eval(node_or_string): ...
def get_docstring(node, clean: bool = True): ...
def copy_location(new_node, old_node): ...
def fix_missing_locations(node): ...
def increment_lineno(node, n: int = 1): ...
