from _typeshed import Incomplete
from paddle.distributed.utils.log_utils import get_logger as get_logger

logger: Incomplete

def init_metric(metric_ptr, metric_yaml_path, cmatch_rank_var: str = '', mask_var: str = '', uid_var: str = '', phase: int = -1, cmatch_rank_group: str = '', ignore_rank: bool = False, bucket_size: int = 1000000) -> None: ...
def print_metric(metric_ptr, name): ...
def print_auc(metric_ptr, is_day, phase: str = 'all'): ...
