from _typeshed import Incomplete
from paddle.base.framework import dygraph_only as dygraph_only, in_dygraph_mode as in_dygraph_mode

def parameters_to_vector(parameters, name: Incomplete | None = None): ...
def vector_to_parameters(vec, parameters, name: Incomplete | None = None): ...
