from ...base.data_feeder import check_type as check_type, check_variable_and_dtype as check_variable_and_dtype
from ...base.layer_helper import LayerHelper as LayerHelper
from ...tensor.manipulation import squeeze as squeeze, unsqueeze as unsqueeze
from ...utils import convert_to_list as convert_to_list
from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.framework import Variable as Variable, in_dygraph_mode as in_dygraph_mode, in_dynamic_or_pir_mode as in_dynamic_or_pir_mode

def avg_pool1d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, exclusive: bool = True, ceil_mode: bool = False, name: Incomplete | None = None): ...
def avg_pool2d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, ceil_mode: bool = False, exclusive: bool = True, divisor_override: Incomplete | None = None, data_format: str = 'NCHW', name: Incomplete | None = None): ...
def avg_pool3d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, ceil_mode: bool = False, exclusive: bool = True, divisor_override: Incomplete | None = None, data_format: str = 'NCDHW', name: Incomplete | None = None): ...
def max_pool1d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, return_mask: bool = False, ceil_mode: bool = False, name: Incomplete | None = None): ...
def max_unpool1d(x, indices, kernel_size, stride: Incomplete | None = None, padding: int = 0, data_format: str = 'NCL', output_size: Incomplete | None = None, name: Incomplete | None = None): ...
def max_unpool2d(x, indices, kernel_size, stride: Incomplete | None = None, padding: int = 0, data_format: str = 'NCHW', output_size: Incomplete | None = None, name: Incomplete | None = None): ...
def max_unpool3d(x, indices, kernel_size, stride: Incomplete | None = None, padding: int = 0, data_format: str = 'NCDHW', output_size: Incomplete | None = None, name: Incomplete | None = None): ...
def max_pool2d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, return_mask: bool = False, ceil_mode: bool = False, data_format: str = 'NCHW', name: Incomplete | None = None): ...
def max_pool3d(x, kernel_size, stride: Incomplete | None = None, padding: int = 0, return_mask: bool = False, ceil_mode: bool = False, data_format: str = 'NCDHW', name: Incomplete | None = None): ...
def adaptive_avg_pool1d(x, output_size, name: Incomplete | None = None): ...
def adaptive_avg_pool2d(x, output_size, data_format: str = 'NCHW', name: Incomplete | None = None): ...
def adaptive_avg_pool3d(x, output_size, data_format: str = 'NCDHW', name: Incomplete | None = None): ...
def adaptive_max_pool1d(x, output_size, return_mask: bool = False, name: Incomplete | None = None): ...
def adaptive_max_pool2d(x, output_size, return_mask: bool = False, name: Incomplete | None = None): ...
def adaptive_max_pool3d(x, output_size, return_mask: bool = False, name: Incomplete | None = None): ...
