from ...base.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from ...base.layer_helper import LayerHelper as LayerHelper
from ...common_ops_import import Variable as Variable
from ...device import get_cudnn_version as get_cudnn_version, is_compiled_with_rocm as is_compiled_with_rocm
from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.framework import in_dygraph_mode as in_dygraph_mode

def affine_grid(theta, out_shape, align_corners: bool = True, name: Incomplete | None = None): ...
def grid_sample(x, grid, mode: str = 'bilinear', padding_mode: str = 'zeros', align_corners: bool = True, name: Incomplete | None = None): ...
def pixel_shuffle(x, upscale_factor, data_format: str = 'NCHW', name: Incomplete | None = None): ...
def pixel_unshuffle(x, downscale_factor, data_format: str = 'NCHW', name: Incomplete | None = None): ...
def channel_shuffle(x, groups, data_format: str = 'NCHW', name: Incomplete | None = None): ...
