from .auto_cast import amp_global_state as amp_global_state
from enum import Enum
from paddle.base import core as core
from paddle.base.data_feeder import check_type as check_type
from paddle.base.dygraph import to_variable as to_variable
from paddle.base.framework import dygraph_only as dygraph_only
from paddle.framework import in_dynamic_mode as in_dynamic_mode

class OptimizerState(Enum):
    INIT = 0
    UNSCALED = 1
    STEPPED = 2

class AmpScaler:
    def __init__(self, enable: bool = True, init_loss_scaling=..., incr_ratio: float = 2.0, decr_ratio: float = 0.5, incr_every_n_steps: int = 1000, decr_every_n_nan_or_inf: int = 1, use_dynamic_loss_scaling: bool = True) -> None: ...
    def scale(self, var): ...
    def minimize(self, optimizer, *args, **kwargs): ...
    def is_enable(self): ...
    def is_use_dynamic_loss_scaling(self): ...
    def get_init_loss_scaling(self): ...
    def set_init_loss_scaling(self, new_init_loss_scaling) -> None: ...
    def get_incr_ratio(self): ...
    def set_incr_ratio(self, new_incr_ratio) -> None: ...
    def get_decr_ratio(self): ...
    def set_decr_ratio(self, new_decr_ratio) -> None: ...
    def get_incr_every_n_steps(self): ...
    def set_incr_every_n_steps(self, new_incr_every_n_steps) -> None: ...
    def get_decr_every_n_nan_or_inf(self): ...
    def set_decr_every_n_nan_or_inf(self, new_decr_every_n_nan_or_inf) -> None: ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict) -> None: ...

class GradScaler(AmpScaler):
    def __init__(self, enable: bool = True, init_loss_scaling=..., incr_ratio: float = 2.0, decr_ratio: float = 0.5, incr_every_n_steps: int = 2000, decr_every_n_nan_or_inf: int = 1, use_dynamic_loss_scaling: bool = True) -> None: ...
    def scale(self, var): ...
    def minimize(self, optimizer, *args, **kwargs): ...
    def step(self, optimizer): ...
    def update(self) -> None: ...
    def unscale_(self, optimizer): ...
    def is_enable(self): ...
    def is_use_dynamic_loss_scaling(self): ...
    def get_init_loss_scaling(self): ...
    def set_init_loss_scaling(self, new_init_loss_scaling) -> None: ...
    def get_incr_ratio(self): ...
    def set_incr_ratio(self, new_incr_ratio) -> None: ...
    def get_decr_ratio(self): ...
    def set_decr_ratio(self, new_decr_ratio) -> None: ...
    def get_incr_every_n_steps(self): ...
    def set_incr_every_n_steps(self, new_incr_every_n_steps) -> None: ...
    def get_decr_every_n_nan_or_inf(self): ...
    def set_decr_every_n_nan_or_inf(self, new_decr_every_n_nan_or_inf) -> None: ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict) -> None: ...
