from paddle.base.data_feeder import convert_dtype as convert_dtype
from paddle.base.layer_helper_base import LayerHelperBase as LayerHelperBase

def set_default_dtype(d) -> None: ...
def get_default_dtype(): ...
