from _typeshed import Incomplete
from paddle import base as base
from paddle.base import core as core
from paddle.base.framework import EagerParamBase as EagerParamBase, Program as Program, Variable as Variable, in_dygraph_mode as in_dygraph_mode

async_save_queue: Incomplete

def clear_async_save_task_queue() -> None: ...
def async_save(obj, path, protocol: int = 4, sync_other_task: bool = False, **configs) -> None: ...
def save(obj, path, protocol: int = 4, **configs) -> None: ...
def load(path, **configs): ...
