from _typeshed import Incomplete
from paddle import base as base
from paddle.base import core as core

def seed(seed): ...
def get_rng_state(device: Incomplete | None = None): ...
def get_cuda_rng_state(): ...
def set_rng_state(state_list, device: Incomplete | None = None) -> None: ...
def set_cuda_rng_state(state_list) -> None: ...
def set_random_seed_generator(name, seed) -> None: ...
def get_random_seed_generator(name): ...
