from _typeshed import Incomplete
from paddle.base.reader import QUEUE_GET_TIMEOUT as QUEUE_GET_TIMEOUT

fork_context: Incomplete

def cache(reader): ...
def map_readers(func, *readers): ...
def shuffle(reader, buf_size): ...
def chain(*readers): ...

class ComposeNotAligned(ValueError): ...

def compose(*readers, **kwargs): ...
def buffered(reader, size): ...
def firstn(reader, n): ...

class XmapEndSignal: ...

def xmap_readers(mapper, reader, process_num, buffer_size, order: bool = False): ...
def multiprocess_reader(readers, use_pipe: bool = True, queue_size: int = 1000): ...
