from paddle.distributed.utils.launch_utils import get_cluster as get_cluster, get_cluster_from_args as get_cluster_from_args, get_gpus as get_gpus, logger as logger

def get_cloud_cluster(args_node_ips, args_node_ip, args_port, selected_devices): ...
def get_cluster_and_pod(args): ...
