LOOKUP_TABLE_TYPE: str

def find_distributed_lookup_table_inputs(program, table_name): ...
def find_distributed_lookup_table_outputs(program, table_name): ...
def find_distributed_lookup_table(program): ...
