from _typeshed import Incomplete

class Command:
    etcd: Incomplete
    prefix: Incomplete
    node_prefix: Incomplete
    np_path: Incomplete
    def __init__(self, server, name) -> None: ...
    def set_np(self, np) -> None: ...
    def scale_np(self, np): ...
    def clean(self) -> None: ...
    def close(self) -> None: ...
