from _typeshed import Incomplete
from paddle.base.framework import Program as Program, static_only as static_only
from paddle.framework import core as core, dygraph_not_support as dygraph_not_support

def load_persistables(executor, dirname, main_program: Incomplete | None = None, filename: Incomplete | None = None) -> None: ...
def is_persistable(var): ...
def save_persistables(executor, dirname, main_program: Incomplete | None = None, filename: Incomplete | None = None): ...
def load_inference_model_distributed(dirname, executor, model_filename: Incomplete | None = None, params_filename: Incomplete | None = None, pserver_endpoints: Incomplete | None = None): ...
