from paddle.base import core as core
from paddle.distributed.fleet.base.private_helper_function import wait_server_ready as wait_server_ready

def gloo_init_parallel_env(rank_id, rank_num, server_endpoint) -> None: ...
def gloo_barrier() -> None: ...
def gloo_release() -> None: ...
