from ...strategy import Strategy as Strategy

class TuningConfig:
    def __init__(self, strategy) -> None: ...
    @property
    def mode(self): ...
    @property
    def profile_start_step(self): ...
    @property
    def profile_end_step(self): ...
    @property
    def project_dir(self): ...
    @property
    def tuning_passes_name(self): ...
    @property
    def max_num_trial(self): ...
    @property
    def early_stop(self): ...
    @property
    def debug(self): ...
    @property
    def dist_strategy(self): ...
    def __getattr__(self, item): ...
