from _typeshed import Incomplete
from paddle.distributed.auto_parallel.static.dist_loader import DistributedDataLoaderFromGenerator as DistributedDataLoaderFromGenerator
from paddle.distributed.auto_parallel.static.process_group import get_all_process_groups as get_all_process_groups, new_process_group as new_process_group
from paddle.framework import Program as Program
from paddle.static import Operator as Operator

def str2bool(v): ...
def parse_args(): ...
def init_process_groups(group_map, rank) -> None: ...
def get_cpp_error_type(error): ...
def create_dataloader(main_program, startup_program, profile_ctx, epochs: int = 1, steps_per_epoch: Incomplete | None = None): ...
def init_comm(profile_ctx) -> None: ...
def load_programs(profile_ctx): ...
def get_executor(): ...
def profiler(args) -> None: ...
