def all_params(mp, pp, sharding, h, l, V): ...
def full_recompute_acts(mp, pp, s, b, h, l): ...
def all_acts(mp, pp, s, b, h, l, a): ...
def to_gb(p): ...
def get_mem(total_cards, parallel_cfg, l, h, a, V, s, gbs): ...
def divisor(num, reverse: bool = False): ...
def get_not_oom_cfgs(cfgs, tuner_cfg): ...
