from _typeshed import Incomplete
from paddle.base import core as core
from paddle.distributed.launch.context import Node as Node
from paddle.distributed.rpc.internal import PythonFunc as PythonFunc
from paddle.distributed.utils.launch_utils import logger as logger
from typing import NamedTuple

class WorkerInfo(NamedTuple):
    name: Incomplete
    rank: Incomplete
    ip: Incomplete
    port: Incomplete

def init_rpc(name, rank: Incomplete | None = None, world_size: Incomplete | None = None, master_endpoint: Incomplete | None = None) -> None: ...
def rpc_sync(to, fn, args: Incomplete | None = None, kwargs: Incomplete | None = None, timeout=...): ...
def rpc_async(to, fn, args: Incomplete | None = None, kwargs: Incomplete | None = None, timeout=...): ...
def shutdown() -> None: ...
def get_worker_info(name): ...
def get_all_worker_infos(): ...
def get_current_worker_info(): ...
