from _typeshed import Incomplete
from paddle.common_ops_import import Variable as Variable

def sum(input, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def max(input, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def min(input, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def auc(stat_pos, stat_neg, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def mae(abserr, total_ins_num, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def rmse(sqrerr, total_ins_num, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def mse(sqrerr, total_ins_num, scope: Incomplete | None = None, util: Incomplete | None = None): ...
def acc(correct, total, scope: Incomplete | None = None, util: Incomplete | None = None): ...
