from _typeshed import Incomplete
from paddle.nn.quant import quant_layers as quant_layers

layer_name_map: Incomplete
fake_quant_input_layers: Incomplete
fake_quant_output_layers: Incomplete
fake_quant_leaf_layers: Incomplete
fake_quant_wrap_layers: Incomplete
spec_channel_axis_layers: Incomplete
weight_op_types: Incomplete
fake_quantize_dequantize_op_types: Incomplete

def load_variable_data(scope, var_name): ...
def find_previous_op(block, var_name): ...
def find_next_ops(block, var_name): ...
def find_parent_layer_and_sub_name(model, name): ...
def program_all_ops(program): ...
def is_leaf_layer(layer): ...
def fp_numpy_to_naive(x_np): ...
