from .base_transformer import BaseTransformer as BaseTransformer
from _typeshed import Incomplete
from paddle.utils import gast as gast

class EarlyReturnTransformer(BaseTransformer):
    root: Incomplete
    def __init__(self, root) -> None: ...
    def transform(self) -> None: ...
    def is_define_return_in_if(self, node): ...
    def visit_block_nodes(self, nodes): ...
    def visit_If(self, node): ...
    def visit_While(self, node): ...
    def visit_For(self, node): ...
    def visit_FunctionDef(self, node): ...
