from _typeshed import Incomplete
from paddle import pir as pir
from paddle.base import core as core
from paddle.base.dygraph.base import switch_to_static_graph as switch_to_static_graph
from paddle.base.framework import get_flags as get_flags

MAX_FILE_PATH_LEN: int

class SubGraphRole:
    Infer: int
    Forward: int
    Backward: int

def get_saving_dir(): ...

class BaseExporter:
    pp_layer: Incomplete
    program: Incomplete
    role: Incomplete
    root_dir: Incomplete
    fetch_col: int
    def __init__(self, partial_program_layer, program, role) -> None: ...
    def save(self) -> None: ...
    def parse_inout(self) -> None: ...
    def translate_into_pir(self): ...
    def generate_saving_path(self): ...
    def verify_saving_dir(self, dir_path) -> None: ...
    def insert_feed_op(self, intputs, rename_prefix) -> None: ...
    def insert_fetch_op(self, outputs, rename_prefix) -> None: ...

class InferExporter(BaseExporter):
    def __init__(self, *args, **kwargs) -> None: ...
    def parse_inout(self): ...

class TrainFwdExporter(BaseExporter):
    raw_inter_outs: Incomplete
    def __init__(self, pp_layer, copy_program, role, raw_inter_outs) -> None: ...
    def parse_inout(self): ...

class TrainBwdExporter(BaseExporter):
    raw_inputs: Incomplete
    raw_outputs: Incomplete
    def __init__(self, pp_layer, copy_program, role, raw_inputs, raw_outputs) -> None: ...
    def parse_inout(self): ...

def pir_exporter(pp_layer, program, role, shared_inputs: Incomplete | None = None, inter_outs: Incomplete | None = None) -> None: ...
