from .base_transformer import BaseTransformer as BaseTransformer
from .utils import ast_to_source_code as ast_to_source_code
from _typeshed import Incomplete
from paddle.utils import gast as gast

cmpop_type_to_str: Incomplete

def cmpop_node_to_str(node): ...

class LogicalTransformer(BaseTransformer):
    root: Incomplete
    def __init__(self, root) -> None: ...
    def transform(self): ...
    def visit_UnaryOp(self, node): ...
    def visit_BoolOp(self, node): ...
