from .program_translator import convert_to_static as convert_to_static, unwrap_decorators as unwrap_decorators
from _typeshed import Incomplete
from paddle.base.framework import Variable as Variable
from paddle.common_ops_import import LayerHelper as LayerHelper
from paddle.static.nn import static_pylayer as static_pylayer

class StaticPyLayerContext:
    saved_vars: Incomplete
    def __init__(self) -> None: ...
    def save_for_backward(self, *tensors) -> None: ...
    def saved_tensor(self): ...
    def mark_not_inplace(self, *args) -> None: ...
    def mark_non_differentiable(self, *args) -> None: ...
    def set_materialize_grads(self, value: bool): ...

class StaticPyLayer:
    dyfunc_self: Incomplete
    static_pylayer_context: Incomplete
    forward_fn_with_ctx: Incomplete
    backward_fn_with_ctx: Incomplete
    def __init__(self, dyfunc_self) -> None: ...
    def apply(self, *args, **kwargs): ...
