from .base_transformer import BaseTransformer as BaseTransformer
from _typeshed import Incomplete

class TypeHintTransformer(BaseTransformer):
    root: Incomplete
    def __init__(self, root) -> None: ...
    def transform(self) -> None: ...
    def visit_FunctionDef(self, node): ...
    def visit_Name(self, node): ...
