from .utils import UndefinedVar as UndefinedVar, create_undefined_variable as create_undefined_variable
from paddle.base.framework import Variable as Variable
from paddle.utils import gast as gast, is_sequence as is_sequence, map_structure as map_structure

def create_undefined_var(name): ...
def create_fill_constant_node(name, value: int = 0): ...
def to_static_variable(x): ...
def create_bool_as_type(x, value: bool = True): ...
def create_bool_node(name, value): ...
