from _typeshed import Incomplete
from paddle.base.layer_helper import LayerHelper as LayerHelper
from paddle.framework import in_dynamic_mode as in_dynamic_mode
from paddle.tensor.linalg import matmul as matmul

def fused_matmul_bias(x, y, bias: Incomplete | None = None, transpose_x: bool = False, transpose_y: bool = False, name: Incomplete | None = None): ...
def fused_linear(x, weight, bias: Incomplete | None = None, transpose_weight: bool = False, name: Incomplete | None = None): ...
def fused_linear_activation(x, y, bias, trans_x: bool = False, trans_y: bool = False, activation: Incomplete | None = None): ...
