from _typeshed import Incomplete

class Registry:
    name: Incomplete
    tab: Incomplete
    def __init__(self, name) -> None: ...
    def register(self, name, value) -> None: ...
    def lookup(self, name): ...

def lookup_fn(optype): ...
def lookup_orig2prim(optype): ...
def lookup_prim2orig(optype): ...
def lookup_jvp(optype): ...
def lookup_transpose(optype): ...
def lookup_composite(optype): ...
def op_position_inputs(op): ...
def op_position_output(op): ...
def REGISTER_FN(op_type, *position_argnames): ...
def REGISTER_ORIG2PRIM(op_type): ...
def REGISTER_COMPOSITE(op_type): ...
def REGISTER_PRIM2ORIG(op_type): ...
def REGISTER_JVP(op_type): ...
def REGISTER_TRANSPOSE(op_type): ...
