from _typeshed import Incomplete
from paddle.base import backward as backward, core as core, framework as framework
from paddle.base.core import prim_config as prim_config
from paddle.incubate.autograd import primx as primx, utils as utils

def forward_grad(outputs, inputs, grad_inputs: Incomplete | None = None): ...
def grad(outputs, inputs, grad_outputs: Incomplete | None = None): ...
def to_prim(blocks, blacklist=..., whitelist=..., start_idx: int = -1, backward_length: int = -1): ...
