from .primops import add as add, fill_const as fill_const
from .primreg import lookup_composite as lookup_composite, lookup_orig2prim as lookup_orig2prim, lookup_prim2orig as lookup_prim2orig, op_position_inputs as op_position_inputs, op_position_output as op_position_output
from .utils import flatten as flatten, flatten_and_remove_none as flatten_and_remove_none, get_input_var_list as get_input_var_list, get_output_var_list as get_output_var_list, map_output_for_composite as map_output_for_composite, prepare_python_api_arguments as prepare_python_api_arguments
from _typeshed import Incomplete
from paddle.base import framework as framework
from paddle.base.core import ops_contain_none as ops_contain_none, prim_config as prim_config
from paddle.base.framework import Operator as Operator, default_main_program as default_main_program
from paddle.incubate.autograd.utils import as_tensors as as_tensors

def topo_path(xs, ys, block: Incomplete | None = None): ...
def output_vars_on_path(path): ...

class VarMap:
    name: Incomplete
    varset: Incomplete
    tab: Incomplete
    def __init__(self, name, varset) -> None: ...
    def add(self, key_var, value_var) -> None: ...
    def add_rec(self, key_vars, value_vars) -> None: ...
    def lookup(self, key_var): ...
    def delete(self, key_var) -> None: ...
    def delete_keyvars(self, key_vars) -> None: ...
    def delete_valuevars(self, value_vars) -> None: ...
    def contain_var(self, key_var): ...
    def contain_value(self, value_var): ...

class Transform:
    block: Incomplete
    vars: Incomplete
    var2dot: Incomplete
    dot2bar: Incomplete
    def __init__(self, block) -> None: ...
    def init_vars(self, block): ...
    def add_vars(self, new_vars) -> None: ...
    def add_vars_rec(self, new_vars) -> None: ...
    def erase_ops(self, ordered_indexes) -> None: ...
    def erase_dots(self, vars_to_erase) -> None: ...
    def var2dot_rec(self, vars): ...
    def dot2bar_rec(self, dots): ...
    def linearize(self, xs, ys, xs_dot: Incomplete | None = None): ...
    def transpose(self, ys_dot, xs_dot, ys_bar: Incomplete | None = None, retain_fwd: bool = False): ...

def orig2prim(block: Incomplete | None = None) -> None: ...
def prim2orig(block: Incomplete | None = None, blacklist: Incomplete | None = None) -> None: ...
