from .phi_ops_map import op_info as op_info, op_map as op_map
from _typeshed import Incomplete
from paddle.base import framework as framework

class PrimOption:
    enable_prim: bool
    def __init__(self) -> None: ...
    def get_status(self): ...
    def set_status(self, flag) -> None: ...

prim_option: Incomplete

def prim_enabled(): ...
def enable_prim() -> None: ...
def disable_prim() -> None: ...

INT_DTYPE_2_STRING: Incomplete

def get_var_block(block, names, is_tensor_list: Incomplete | None = None): ...
def get_input_var_list(op): ...
def prepare_python_api_arguments(op): ...
def get_output_var_list(op): ...
def map_output_for_composite(op): ...
def flatten(inp): ...
def flatten_and_remove_none(inp): ...
def as_tensors(xs): ...
