from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.framework import dygraph_only as dygraph_only
from paddle.base.layer_helper import LayerHelper as LayerHelper

def relu(x, name: Incomplete | None = None): ...
def softmax(x, axis: int = -1, name: Incomplete | None = None): ...
def relu6(x, name: Incomplete | None = None): ...
def leaky_relu(x, negative_slope: float = 0.01, name: Incomplete | None = None): ...
