from ...binary import add as add
from _typeshed import Incomplete
from paddle import in_dynamic_mode as in_dynamic_mode
from paddle.base.layer_helper import LayerHelper as LayerHelper
from paddle.utils import convert_to_list as convert_to_list

def conv3d(x, weight, bias: Incomplete | None = None, stride: int = 1, padding: int = 0, dilation: int = 1, groups: int = 1, data_format: str = 'NDHWC', name: Incomplete | None = None): ...
def subm_conv3d(x, weight, bias: Incomplete | None = None, stride: int = 1, padding: int = 0, dilation: int = 1, groups: int = 1, data_format: str = 'NDHWC', key: Incomplete | None = None, name: Incomplete | None = None): ...
def conv2d(x, weight, bias: Incomplete | None = None, stride: int = 1, padding: int = 0, dilation: int = 1, groups: int = 1, data_format: str = 'NHWC', name: Incomplete | None = None): ...
def subm_conv2d(x, weight, bias: Incomplete | None = None, stride: int = 1, padding: int = 0, dilation: int = 1, groups: int = 1, data_format: str = 'NHWC', key: Incomplete | None = None, name: Incomplete | None = None): ...
