from _typeshed import Incomplete

__all__ = ['get_weights_path_from_url']

class tqdm:
    total: Incomplete
    n: int
    def __init__(self, total: Incomplete | None = None) -> None: ...
    def update(self, n) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

def get_weights_path_from_url(url, md5sum: Incomplete | None = None): ...
