from ..base import core as core
from _typeshed import Incomplete

def Singleton(cls): ...

class OpUpdateInfoHelper:
    def __init__(self, info) -> None: ...
    def verify_key_value(self, name: str = ''): ...

class OpLastCheckpointChecker:
    raw_version_map: Incomplete
    checkpoints_map: Incomplete
    def __init__(self) -> None: ...
    def filter_updates(self, op_name, type=..., key: str = ''): ...
