def sum_ranges(ranges): ...
def merge_self_ranges(src_ranges, is_sorted: bool = False): ...
def merge_ranges(range_list1, range_list2, is_sorted: bool = False): ...
def intersection_ranges(range_list1, range_list2, is_sorted: bool = False): ...
def subtract_ranges(range_list1, range_list2, is_sorted: bool = False): ...
