from _typeshed import Incomplete

class Stack:
    items: Incomplete
    def __init__(self) -> None: ...
    def push(self, item) -> None: ...
    def pop(self): ...
    def is_empty(self): ...
    def peek(self): ...

class Event:
    reader_cost_averager: Incomplete
    batch_cost_averager: Incomplete
    total_samples: int
    total_iters: int
    skip_iter: int
    reader_records: Incomplete
    batch_records: Incomplete
    speed_records: Incomplete
    reader: Incomplete
    need_record: bool
    speed_mode: str
    speed_unit: str
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def record_reader(self, usetime) -> None: ...
    def record_batch(self, usetime, num_samples: Incomplete | None = None) -> None: ...
    def reader_average(self): ...
    def batch_average(self): ...
    def speed_average(self): ...
    def get_summary(self): ...

class Hook:
    def begin(self, benchmark) -> None: ...
    def end(self, benchmark) -> None: ...
    def before_reader(self, benchmark) -> None: ...
    def after_reader(self, benchmark) -> None: ...
    def after_step(self, benchmark) -> None: ...

class TimerHook(Hook):
    start_time: Incomplete
    start_reader: Incomplete
    def __init__(self) -> None: ...
    def begin(self, benchmark) -> None: ...
    def before_reader(self, benchmark) -> None: ...
    def after_reader(self, benchmark) -> None: ...
    def after_step(self, benchmark) -> None: ...
    def end(self, benchmark) -> None: ...

class TimeAverager:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def record(self, usetime, num_samples: Incomplete | None = None) -> None: ...
    def get_average(self): ...
    def get_ips_average(self): ...
    def get_step_average(self): ...

class Benchmark:
    num_samples: Incomplete
    hooks: Incomplete
    current_event: Incomplete
    events: Incomplete
    def __init__(self) -> None: ...
    def step(self, num_samples: Incomplete | None = None) -> None: ...
    def step_info(self, unit): ...
    def begin(self) -> None: ...
    def before_reader(self) -> None: ...
    def after_reader(self) -> None: ...
    def after_step(self) -> None: ...
    def end(self) -> None: ...
    def check_if_need_record(self, reader) -> None: ...

def benchmark(): ...
