from .. import core as core
from ..executor import global_scope as global_scope
from ..framework import default_main_program as default_main_program, default_startup_program as default_startup_program
from _typeshed import Incomplete

def monkey_patch_reader_methods(reader): ...
def __create_shared_decorated_reader__(op_type, reader, attrs): ...
def __create_unshared_decorated_reader__(op_type, reader, attrs, name: Incomplete | None = None): ...
