from ..data_feeder import check_variable_and_dtype as check_variable_and_dtype
from ..framework import OpProtoHolder as OpProtoHolder, Variable as Variable, convert_np_dtype_to_dtype_ as convert_np_dtype_to_dtype_, core as core, in_dygraph_mode as in_dygraph_mode
from ..layer_helper import LayerHelper as LayerHelper
from ..proto import framework_pb2 as framework_pb2
from _typeshed import Incomplete

def escape_math(text): ...
def generate_layer_fn(op_type): ...
def generate_activation_fn(op_type): ...
def generate_inplace_fn(inplace_op_type): ...
def autodoc(comment: str = ''): ...
def templatedoc(op_type: Incomplete | None = None): ...
def add_sample_code(func, sample_code) -> None: ...
