from _typeshed import Incomplete

class _DatasetFetcher:
    dataset: Incomplete
    auto_collate_batch: Incomplete
    collate_fn: Incomplete
    drop_last: Incomplete
    def __init__(self, dataset, auto_collate_batch, collate_fn, drop_last) -> None: ...
    def fetch(self, batch_indices, done_event: Incomplete | None = None) -> None: ...

class _IterableDatasetFetcher(_DatasetFetcher):
    dataset_iter: Incomplete
    def __init__(self, dataset, auto_collate_batch, collate_fn, drop_last) -> None: ...
    def fetch(self, batch_indices, done_event: Incomplete | None = None): ...

class _MapDatasetFetcher(_DatasetFetcher):
    def __init__(self, dataset, auto_collate_batch, collate_fn, drop_last) -> None: ...
    def fetch(self, batch_indices, done_event: Incomplete | None = None): ...
