__all__ = ['LazyGuard']

class LazyInitHelper:
    def __init__(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args, **kwargs) -> None: ...
    @property
    def state(self): ...

class LazyGuard:
    def __enter__(self) -> None: ...
    def __exit__(self, *args, **kwargs) -> None: ...
