from _typeshed import Incomplete
from paddle import framework as framework

class HeterParallelOptimizer:
    def __init__(self, optimizer, strategy) -> None: ...
    def step(self) -> None: ...
    def minimize(self, loss, startup_program: Incomplete | None = None, parameters: Incomplete | None = None, no_grad_set: Incomplete | None = None): ...
    def __getattr__(self, item): ...
