from .device import Device as Device
from _typeshed import Incomplete

class Node:
    device: Incomplete
    ip: Incomplete
    free_ports: Incomplete
    def __init__(self) -> None: ...
    hostname: Incomplete
    def get_host_ip(self): ...
    def get_free_ports(self, n: int = 1): ...
    def get_ports_occupied(self): ...
    def get_free_port(self): ...
    @classmethod
    def is_server_ready(self, ip, port): ...
