from ..base_quanter import BaseQuanter as BaseQuanter
from ..factory import QuanterFactory as QuanterFactory
from _typeshed import Incomplete
from paddle.base.data_feeder import check_variable_and_dtype as check_variable_and_dtype
from paddle.framework import ParamAttr as ParamAttr, core as core
from paddle.nn.initializer import Constant as Constant
from paddle.utils import unique_name as unique_name

class FakeQuanterWithAbsMaxObserver(QuanterFactory):
    def __init__(self, moving_rate: float = 0.9, bit_length: int = 8, dtype: str = 'float32', name: Incomplete | None = None) -> None: ...

class FakeQuanterWithAbsMaxObserverLayer(BaseQuanter):
    def __init__(self, layer, name: Incomplete | None = None, moving_rate: float = 0.9, bit_length: int = 8, dtype: str = 'float32') -> None: ...
    def dynamic_forward(self, input): ...
    def static_forward(self, input): ...
    def forward(self, input): ...
    def bit_length(self): ...
    def quant_axis(self): ...
    def scales(self): ...
    def zero_points(self) -> None: ...
