from _typeshed import Incomplete
from collections.abc import Generator
from paddle.framework import core as core

class SotProfiler:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def enable(self, tag: Incomplete | None = None) -> None: ...
    def disable(self) -> None: ...

def EventGuard(event_name, event_level: int = 0) -> Generator[None]: ...

EventGuard: Incomplete

def event_register(event_name, event_level: int = 0): ...
