import types
from typing import Callable, TypeVar
from typing_extensions import ParamSpec

T = TypeVar('T')
P = ParamSpec('P')
NO_BREAKGRAPH_CODES: set[types.CodeType]
NO_FALLBACK_CODES: set[types.CodeType]

def assert_true(input: bool): ...
def print(*args, **kwargs) -> None: ...
def breakpoint() -> None: ...
def check_no_breakgraph(fn: Callable[P, T]) -> Callable[P, T]: ...
def breakgraph() -> None: ...
def check_no_fallback(fn: Callable[P, T]) -> Callable[P, T]: ...
def fallback() -> None: ...
def in_sot(): ...
