from _typeshed import Incomplete
from paddle.base import core as core
from paddle.base.framework import Program as Program
from paddle.distributed.auto_parallel.static.converter import Converter as Converter
from paddle.distributed.auto_parallel.static.dist_context import get_default_distributed_context as get_default_distributed_context
from paddle.distributed.auto_parallel.static.utils import is_backward_op as is_backward_op, is_forward_op as is_forward_op, is_loss_op as is_loss_op
from paddle.static.io import deserialize_program as deserialize_program

class AutoAlignTool:
    def __init__(self, program: Program, step: int = 1, fetch_list: Incomplete | None = None) -> None: ...
    def set_step(self, step) -> None: ...
    def get_var(self, level, step): ...
    def set_program(self, program: Program): ...
    def get_loss_lr_var(self): ...
    def get_data_var(self): ...
    def get_param_var(self): ...
    def get_param_grad_var(self): ...
    def get_forward_tmp_var(self): ...
    def get_backward_tmp_var(self): ...
    def save(self, save_dir, vars, fetch_list, dist_context: Incomplete | None = None) -> None: ...
    @staticmethod
    def load(save_dir): ...
    @staticmethod
    def convert_src_tensor_2_dst_tensor(vars_list, src_attr_map, dst_attr_map): ...
    @staticmethod
    def find_diff_vars(fixed_vars_map, query_vars_map): ...
    @staticmethod
    def diff_informations(right_dir, wrong_dir): ...
    @staticmethod
    def diff_informations_from_dirs(right_dirs, wrong_dirs): ...
