from ...utils.log_utils import get_logger as get_logger

class Converter:
    def __init__(self, tensors_dict, pre_strategy, cur_strategy) -> None: ...
    def convert(self, strict: bool = True): ...
    def convert_with_prefix_match(self, tensors_dict, tensor_not_in_pre, tensor_not_in_cur): ...
    @staticmethod
    def merge_and_slice(tensor_list, pre_dist_attr, cur_dist_attr): ...
    @staticmethod
    def merge_with_dist_attr(tensor_list, dist_attr): ...
    @staticmethod
    def slice_with_dist_attr(tensor, dist_attr): ...
    @staticmethod
    def merge(partition_tensor_list, tensor, partition_index, complete_shape) -> None: ...
    @staticmethod
    def split(complete_tensor, partition_index_list, length): ...
