from ...utils.log_utils import get_logger as get_logger
from .utils import get_dist_attr as get_dist_attr
from paddle.framework import core as core

def check_filename(re_exp, filename): ...

class DistributedSaver:
    def __init__(self) -> None: ...
    def save(self, path, serial_program, dist_main_program, dist_context) -> None: ...
    def load(self, path, load_optimizer: bool = True): ...
    def save_inference_model(self, path, feed_vars, fetch_vars, exe, **kwargs) -> None: ...
