from .dist_attribute import OperatorDistAttr as OperatorDistAttr
from .utils import __no_shape_var_type__ as __no_shape_var_type__, convert_to_shard_spec as convert_to_shard_spec, verify_shard_spec as verify_shard_spec
from _typeshed import Incomplete
from paddle.static import Variable as Variable

class DistributedOperator:
    def __init__(self, serial_op, dist_attr: Incomplete | None = None) -> None: ...
    @property
    def serial_op(self): ...
    @property
    def dist_attr(self): ...
    @dist_attr.setter
    def dist_attr(self, dist_attr) -> None: ...
    def get_serial_input(self, name): ...
    def get_serial_output(self, name): ...
    def validate_dist_attr(self): ...
    def __deepcopy__(self, memo): ...

class DistributedOperatorHelper:
    def __init__(self, serial_op, process_mesh, in_dims_mappings, out_dims_mappings, kwargs) -> None: ...
    def __call__(self, *args, **kwargs): ...
