class Node:
    def __init__(self, id, **attrs) -> None: ...
    @property
    def id(self): ...
    @property
    def attrs(self): ...
    def __getitem__(self, attr_name): ...
    def __setitem__(self, attr_name, attr_value) -> None: ...
    def __contains__(self, attr_name) -> bool: ...

class Edge:
    def __init__(self, src_id, tgt_id, **attrs) -> None: ...
    @property
    def src_id(self): ...
    @property
    def tgt_id(self): ...
    @property
    def attrs(self): ...
    def __getitem__(self, attr_name): ...
    def __setitem__(self, attr_name, attr_value) -> None: ...
    def __contains__(self, attr_name) -> bool: ...

class Graph:
    def __init__(self, **attrs) -> None: ...
    @property
    def nodes(self): ...
    @property
    def attrs(self): ...
    @property
    def adjs(self): ...
    def add_node(self, node_id, **attrs): ...
    def add_edge(self, src_id, tgt_id, **attrs): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, node_id): ...
    def __contains__(self, node_id) -> bool: ...
