from .cluster import DeviceType as DeviceType
from .graph import Graph as Graph
from .process_group import get_process_group as get_process_group

def is_collective_comm_op(op): ...
def is_p2p_comm_op(op): ...
def get_dtype_bytes(dtype): ...
def get_comm_volume(comm_op, src_rank, tgt_rank): ...
def analyze_comm_requirements_from_op(op, rank, g_process_group_map): ...
def analyze_requirements_for_program(src_info, rank): ...
def build_process_graph(distributed_program): ...
def build_cluster_graph(cluster): ...
def mapping(distributed_program, cluster): ...
