from _typeshed import Incomplete
from paddle.framework import core as core

class ProcessMesh(core.ProcessMesh):
    def __init__(self, mesh, dim_names: Incomplete | None = None) -> None: ...
    @property
    def mesh(self): ...

def compute_compatible_process_mesh(process_meshes): ...
def merge_process_mesh(process_meshes): ...
