from _typeshed import Incomplete
from paddle.base.log_helper import get_logger as get_logger

color_map: Incomplete

def parse_args(): ...
def process_job_log(log_data, device_id, multi_machine_idx: int = -1): ...
def main() -> None: ...
