from _typeshed import Incomplete

def call_cmd(cmd, err_msg, default_value): ...

class SingleNodeTopology:
    pcie_latency: float
    pcie_bandwidth: Incomplete
    nvlink_bandwidth: float
    nb_devices: int
    machine: Incomplete
    devices: Incomplete
    links: Incomplete
    json_object: Incomplete
    def __init__(self) -> None: ...
    def calculate_cpu_flops(self) -> None: ...
    def pcie_gen2bandwidth(self, pcie_generation): ...
    def model2gflops(self, model): ...
    def get_link_bandwidth(self, source_id, target_id): ...
    def get_host_info(self) -> None: ...
    def get_device_info(self) -> None: ...
    def get_link_info(self) -> None: ...
    def detect(self) -> None: ...
    def dump(self, output_path) -> None: ...
