from _typeshed import Incomplete

class SotErrorBase(Exception):
    def __init__(self, *args, **kwargs) -> None: ...
    def print(self) -> None: ...

class InnerError(SotErrorBase): ...
class HasNoAttributeError(InnerError): ...

class FallbackError(SotErrorBase):
    disable_eval_frame: Incomplete
    def __init__(self, msg, disable_eval_frame: bool = False) -> None: ...

class BreakGraphError(SotErrorBase): ...

def inner_error_default_handler(func, message_fn): ...
