from _typeshed import Incomplete

def is_inplace_api(func): ...
def get_tensor_methods(): ...
def get_paddle_api(): ...

paddle_tensor_methods: Incomplete
paddle_api_list: Incomplete
paddle_api_module_prefix: Incomplete
break_graph_set: Incomplete
break_graph_tensor_method: Incomplete
not_supported_paddle_layer: Incomplete

def is_not_supported_paddle_layer(layer_class): ...
def is_break_graph_tensor_methods(method_name): ...
def add_break_graph_apis(apis: list): ...
