from _typeshed import Incomplete

FLOAT_TYPE_DICT: Incomplete
PADDLE_TO_NUMBER: Incomplete
NUMBER_TO_DTYPE: Incomplete

def is_float_tensor(tensor): ...
def get_tensor_dtype(dtype): ...
def paddle_2_number(dtype): ...
def number_2_dtype(number): ...
def get_tensor_bytes(tensor): ...
