from _typeshed import Incomplete

class Server:
    def __init__(self) -> None: ...

class Worker:
    def __init__(self) -> None: ...

class DownpourServer(Server):
    def __init__(self) -> None: ...
    def add_sparse_table(self, table_id, strategy) -> None: ...
    def add_dense_table(self, table_id, param_var, grad_var, strategy, sparse_table_names): ...
    def add_data_norm_table(self, table_id, learning_rate, param_var, grad_var, strategy, sparse_table_names): ...
    def add_sparse_optimizer(self, sgd, strategy, prefix) -> None: ...
    def add_sparse_table_common_config(self, table, strategy) -> None: ...
    def get_desc(self): ...

class DownpourWorker(Worker):
    window: Incomplete
    def __init__(self, window) -> None: ...
    def add_sparse_table(self, table_id, slot_key_vars, slot_value_vars, slot_value_grads: Incomplete | None = None) -> None: ...
    def add_dense_table(self, table_id, learning_rate, param_vars, grad_vars, dense_start_table_id, sparse_table_names) -> None: ...
    def get_desc(self): ...
