from paddle.base.data_feeder import check_dtype as check_dtype, convert_dtype as convert_dtype
from paddle.base.framework import Variable as Variable

def convert_out_size_to_list(out_size, op_type): ...
def get_out_size_tensor_inputs(inputs, attrs, out_size, op_type) -> None: ...
def reshape_lhs_rhs(x, y): ...
