from _typeshed import Incomplete
from paddle.distributed.communication import stream as stream

def alltoall(in_tensor_list, out_tensor_list, group: Incomplete | None = None, sync_op: bool = True): ...
def alltoall_single(in_tensor, out_tensor, in_split_sizes: Incomplete | None = None, out_split_sizes: Incomplete | None = None, group: Incomplete | None = None, sync_op: bool = True): ...
