from _typeshed import Incomplete
from paddle.distributed.communication import stream as stream

def send(tensor, dst: int = 0, group: Incomplete | None = None, sync_op: bool = True): ...
def isend(tensor, dst, group: Incomplete | None = None): ...
