from ..fp16_utils import find_true_post_op as find_true_post_op, find_true_prev_op as find_true_prev_op
from .amp_lists import AutoMixedPrecisionListsBF16 as AutoMixedPrecisionListsBF16
from _typeshed import Incomplete
from collections.abc import Generator
from paddle.base import core as core, framework as framework, global_scope as global_scope
from paddle.base.log_helper import get_logger as get_logger
from paddle.base.wrapped_decorator import signature_safe_contextmanager as signature_safe_contextmanager

def convert_float_to_uint16(in_list): ...
def bf16_guard() -> Generator[None]: ...
def are_post_ops_bf16(post_ops, keep_fp32_ops): ...
def cast_initializers_to_bf16(startup_prog, amp_lists, block, all_ops, keep_fp32_ops, to_bf16_var_names: Incomplete | None = None) -> None: ...
def cast_model_to_bf16(program, startup_prog: Incomplete | None = None, amp_lists: Incomplete | None = None, use_bf16_guard: bool = True): ...
def cast_parameters_to_bf16(place, program, scope: Incomplete | None = None, to_bf16_var_names: Incomplete | None = None) -> None: ...
def rewrite_program_bf16(main_prog, amp_lists: Incomplete | None = None) -> None: ...
