import abc
import numpy as np
import paddle
from collections.abc import Iterable
from paddle.nn import Layer as Layer

class BaseQuanter(Layer, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @abc.abstractmethod
    def forward(self, input): ...
    @abc.abstractmethod
    def scales(self) -> paddle.Tensor | np.ndarray: ...
    @abc.abstractmethod
    def zero_points(self) -> paddle.Tensor | np.ndarray: ...
    @abc.abstractmethod
    def quant_axis(self) -> int | Iterable: ...
    @abc.abstractmethod
    def bit_length(self): ...
