from _typeshed import Incomplete

class Registry:
    name: Incomplete
    rules: Incomplete
    def __init__(self, name) -> None: ...
    def register(self, op_type, rule) -> None: ...
    def lookup(self, op_type): ...

def register_decomp(op_type): ...
def get_decomp_rule(op_type): ...
