from ...base.framework import Variable as Variable
from _typeshed import Incomplete

def normalize(img, mean, std, data_format: str = 'CHW'): ...
def to_grayscale(img, num_output_channels: int = 1, data_format: str = 'CHW'): ...
def affine(img, matrix, interpolation: str = 'nearest', fill: Incomplete | None = None, data_format: str = 'CHW'): ...
def rotate(img, angle, interpolation: str = 'nearest', expand: bool = False, center: Incomplete | None = None, fill: Incomplete | None = None, data_format: str = 'CHW'): ...
def perspective(img, coeffs, interpolation: str = 'nearest', fill: Incomplete | None = None, data_format: str = 'CHW'): ...
def vflip(img, data_format: str = 'CHW'): ...
def hflip(img, data_format: str = 'CHW'): ...
def crop(img, top, left, height, width, data_format: str = 'CHW'): ...
def erase(img, i, j, h, w, v, inplace: bool = False): ...
def center_crop(img, output_size, data_format: str = 'CHW'): ...
def pad(img, padding, fill: int = 0, padding_mode: str = 'constant', data_format: str = 'CHW'): ...
def resize(img, size, interpolation: str = 'bilinear', data_format: str = 'CHW'): ...
def adjust_brightness(img, brightness_factor): ...
def adjust_contrast(img, contrast_factor): ...
def adjust_saturation(img, saturation_factor): ...
def adjust_hue(img, hue_factor): ...
