from _typeshed import Incomplete
from collections import OrderedDict

class _LRUSharedCache(OrderedDict):
    limit: int
    def __init__(self) -> None: ...
    def get(self, key): ...
    def __setitem__(self, key, value) -> None: ...

shared_cache: Incomplete

def init_reductions() -> None: ...
