from .base_cost import Cost as Cost
from _typeshed import Incomplete
from paddle.distributed.auto_parallel.static.dist_tensor import DistributedTensor as DistributedTensor
from paddle.static import Variable as Variable

class TensorCost:
    def __init__(self, tensor: Incomplete | None = None, dist_tensor: Incomplete | None = None, shape: Incomplete | None = None, dtype: Incomplete | None = None) -> None: ...
    @property
    def tensor(self): ...
    @property
    def dist_tensor(self): ...
    @property
    def shape(self): ...
    @property
    def dtype(self): ...
    @property
    def cost(self): ...
    def calc_cost(self): ...
