from _typeshed import Incomplete

def memory_optimize(input_program, skip_opt_set: Incomplete | None = None, print_log: bool = False, level: int = 0, skip_grads: bool = True) -> None: ...
def release_memory(input_program, skip_opt_set: Incomplete | None = None) -> None: ...
