from _typeshed import Incomplete
from paddle.distributed.fleet.base.strategy_group import StrategyGroupBase as StrategyGroupBase

class OrthogonalStrategy:
    def __init__(self, list_of_strategy, fused_strategy_dict={}, strategy_rank_list: Incomplete | None = None) -> None: ...
    def strategy_group(self, name): ...
    def fused_strategy_group(self, name): ...
    def rank_in_strategy(self, name): ...
