def create_graph(optimizer_list): ...
def topo_sort(edge, indegree): ...
def floyd(edge): ...
def maximum_path_len_algo(optimizer_list): ...

class StrategyCompilerBase:
    def __init__(self) -> None: ...

class StrategyCompiler(StrategyCompilerBase):
    def __init__(self) -> None: ...
    def generate_optimizer(self, loss, role_maker, optimizer, user_defined_strategy, meta_optimizer_list, graph_optimizer_list): ...
