from ..utils.fs import FS as FS
from .graphviz import GraphPreviewGenerator as GraphPreviewGenerator
from _typeshed import Incomplete
from paddle import framework as framework
from paddle.base import core as core
from paddle.base.proto import framework_pb2 as framework_pb2
from paddle.static import Program as Program

class UtilFactory: ...

class UtilBase:
    role_maker: Incomplete
    dist_strategy: Incomplete
    def __init__(self) -> None: ...
    def all_reduce(self, input, mode: str = 'sum', comm_world: str = 'worker'): ...
    def barrier(self, comm_world: str = 'worker') -> None: ...
    def all_gather(self, input, comm_world: str = 'worker'): ...
    def get_heter_file_shard(self, files): ...
    def get_file_shard(self, files): ...
    def print_on_rank(self, message, rank_id) -> None: ...

def draw_block_graphviz(block, highlights: Incomplete | None = None, path: str = './temp.dot'): ...
