from enum import Enum

class MaskAlgo(Enum):
    MASK_1D = 'get_mask_1d'
    MASK_2D_GREEDY = 'get_mask_2d_greedy'
    MASK_2D_BEST = 'get_mask_2d_best'

class CheckMethod(Enum):
    CHECK_1D = 'check_mask_1d'
    CHECK_2D = 'check_mask_2d'
    @staticmethod
    def get_checking_method(mask_algo): ...

def calculate_density(x): ...
def check_mask_1d(mat, n, m): ...
def get_mask_1d(mat, n, m): ...
def check_mask_2d(mat, n, m): ...
def get_mask_2d_greedy(mat, n, m): ...
def get_mask_2d_best(mat, n, m): ...
def create_mask(tensor, func_name=..., n: int = 2, m: int = 4): ...
def check_sparsity(tensor, func_name=..., n: int = 2, m: int = 4): ...
