from paddle import static as static
from paddle.base import core as core

class CostModel:
    def __init__(self) -> None: ...
    def build_program(self): ...
    def profile_measure(self, startup_program, main_program, device: str = 'gpu', fetch_cost_list=['time']) -> None: ...
    def static_cost_data(self): ...
    def get_static_op_time(self, op_name, forward: bool = True, dtype: str = 'float32'): ...
