from paddle.incubate.distributed.fleet.parameter_server.ir.trainer_pass import create_heter_program as create_heter_program, create_trainer_program as create_trainer_program, find_block_joints as find_block_joints, find_heter_ops as find_heter_ops, union_forward_gradient_op as union_forward_gradient_op

def split_heter_worker_ops_pass(program, config, stage_id, device): ...
def split_trainer_ops_pass(program, config, default_device: str = 'cpu'): ...
