class PSDispatcher:
    def __init__(self, pserver_endpoints) -> None: ...
    @property
    def eps(self): ...
    def reset(self) -> None: ...
    def dispatch(self, varlist) -> None: ...

class HashName(PSDispatcher):
    def __init__(self, pserver_endpoints) -> None: ...
    def dispatch(self, varlist): ...

class RoundRobin(PSDispatcher):
    def __init__(self, pserver_endpoints) -> None: ...
    def dispatch(self, varlist): ...
