from _typeshed import Incomplete
from paddle.framework import core as core
from paddle.incubate.distributed.fleet.parameter_server.ir.public import get_sparse_tablename as get_sparse_tablename, get_sparse_tablenames as get_sparse_tablenames, is_distributed_sparse_op as is_distributed_sparse_op

LEARNING_RATE_DECAY_COUNTER: str
OP_ROLE_VAR_ATTR_NAME: Incomplete
RPC_OP_ROLE_ATTR_NAME: Incomplete
OPT_OP_ROLE_ATTR_VALUE: Incomplete
LR_SCHED_OP_ROLE_ATTR_VALUE: Incomplete

def get_op_by_type(block, op_type): ...
def add_listen_and_serv_pass(program, config): ...
def add_rpc_global_flags_pass(program, config): ...
def add_optimizer_pass(program, config): ...
def large_scale_sparse_pass(program, main_program, config, is_startup: bool = False): ...
def get_distributed_from_listen_and_serv(program, origin_program): ...
def delete_unused_in_main_pass(program, config): ...
def delete_unused_in_startup_pass(program, main_program, config): ...
def build_pserver_startup_program_pass(program, p_main_program, config): ...
def add_geo_optimizer_pass(program, config): ...
