from _typeshed import Incomplete

class UnionFind:
    def __init__(self, elementes: Incomplete | None = None) -> None: ...
    def find(self, x): ...
    def union(self, x, y) -> None: ...
    def is_connected(self, x, y): ...
