class JobMode:
    COLLECTIVE: str
    PS: str
    HETER: str

class Job:
    def __init__(self, jid: str = 'default', mode=..., nnodes: str = '1') -> None: ...
    @property
    def mode(self): ...
    @property
    def id(self): ...
    @property
    def elastic(self): ...
    @property
    def replicas(self): ...
    @property
    def replicas_min(self): ...
    @property
    def replicas_max(self): ...
    @replicas.setter
    def replicas(self, replicas) -> None: ...
    def set_replicas(self, nnodes: str): ...
