from .container import Container as Container
from .status import Status as Status
from _typeshed import Incomplete

class PodSepc:
    def __init__(self) -> None: ...

class Pod(PodSepc):
    def __init__(self) -> None: ...
    def failed_container(self): ...
    @property
    def name(self): ...
    @property
    def replicas(self): ...
    @replicas.setter
    def replicas(self, r) -> None: ...
    @property
    def rank(self): ...
    @rank.setter
    def rank(self, r) -> None: ...
    @property
    def restart(self): ...
    @property
    def containers(self): ...
    def add_container(self, c) -> None: ...
    @property
    def init_containers(self): ...
    def add_init_container(self, c) -> None: ...
    @property
    def exit_code(self): ...
    def deploy(self) -> None: ...
    def stop(self, sigint: int = 15, timeout: Incomplete | None = None): ...
    def join(self, timeout: Incomplete | None = None): ...
    @property
    def status(self): ...
    def reset(self) -> None: ...
    def is_failed(self): ...
    def is_completed(self): ...
    def is_running(self): ...
    def logs(self, idx: Incomplete | None = None) -> None: ...
    def tail(self, idx: Incomplete | None = None) -> None: ...
    def watch(self, all_list=..., any_list=..., interval: int = 1, timeout: int = -1): ...
