from _typeshed import Incomplete
from paddle import version as version
from paddle.base.data_feeder import check_dtype as check_dtype
from paddle.base.framework import convert_np_dtype_to_dtype_ as convert_np_dtype_to_dtype_
from paddle.device.cuda import get_device_capability as get_device_capability
from paddle.framework import LayerHelper as LayerHelper, in_dynamic_mode as in_dynamic_mode, in_dynamic_or_pir_mode as in_dynamic_or_pir_mode

def weight_quantize(x, algo: str = 'weight_only_int8', arch: Incomplete | None = None): ...
def weight_dequantize(x, scale, algo: str = 'weight_only_int8', out_dtype: str = 'float16'): ...
def weight_only_linear(x, weight, bias: Incomplete | None = None, weight_scale: Incomplete | None = None, weight_dtype: str = 'int8', arch: Incomplete | None = None): ...
def llm_int8_linear(x, weight, bias: Incomplete | None = None, weight_scale: Incomplete | None = None, threshold: float = 6.0): ...
