from ..layer.layers import Layer as Layer
from _typeshed import Incomplete

class Stub(Layer):
    def __init__(self, observer: Incomplete | None = None) -> None: ...
    def forward(self, input): ...

class QuanterStub(Layer):
    def __init__(self, layer: Stub, q_config) -> None: ...
    def forward(self, input): ...
