from .control_flow import BlockGuard as BlockGuard, copy_var_to_parent_block as copy_var_to_parent_block
from _typeshed import Incomplete
from paddle.base import core as core
from paddle.base.framework import Variable as Variable
from paddle.common_ops_import import LayerHelper as LayerHelper, check_type as check_type, in_dygraph_mode as in_dygraph_mode
from paddle.utils import flatten as flatten, map_structure as map_structure

class StaticPyLayerBlockGuard(BlockGuard):
    block_manager: Incomplete
    def __init__(self, block_manager) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...

class StaticPyLayerBlock:
    fwd_inputs: Incomplete
    fwd_outputs: Incomplete
    context: Incomplete
    helper: Incomplete
    fwd_op_id: Incomplete
    var_old_to_new: Incomplete
    def __init__(self, inputs, name: Incomplete | None = None, pylayer_context: Incomplete | None = None) -> None: ...
    is_backward_block: Incomplete
    def block(self, is_backward_block: bool = False): ...
    @property
    def forward_block_index(self): ...
    @property
    def backward_block_index(self): ...
    @property
    def fwd_op_index(self): ...
    def complete_forward_block(self) -> None: ...
    def complete_backward_block(self) -> None: ...
    def complete(self): ...

def copy_var_from_parent_block(parent_block_var, layer_helper): ...
def static_pylayer(forward_fn, inputs, backward_fn: Incomplete | None = None, name: Incomplete | None = None): ...
