from ...random import determinate_rng as determinate_rng, is_enable_auto_rand_ctrl as is_enable_auto_rand_ctrl
from .common import DistributedOperatorImplContainer as DistributedOperatorImplContainer, register_distributed_operator_impl as register_distributed_operator_impl, register_distributed_operator_impl_container as register_distributed_operator_impl_container
from .dist_eltwise import DistributedElementwiseImpl0 as DistributedElementwiseImpl0

class DistributedFlashAttn(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...

class DistributedFlashAttnImpl0(DistributedElementwiseImpl0):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op): ...
    def is_output_compatible(self, dist_op): ...
    def is_auto_compatible(self, dist_op): ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
