from ..utils import compute_compatible_and_update_dim_mapping as compute_compatible_and_update_dim_mapping
from .common import DistributedOperatorImpl as DistributedOperatorImpl, DistributedOperatorImplContainer as DistributedOperatorImplContainer
from .dist_default import DistributedDefaultImpl0 as DistributedDefaultImpl0

class DistributedAssign(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...

class DistributedAssignImpl(DistributedOperatorImpl):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op): ...
    def is_output_compatible(self, dist_op): ...
    def is_auto_compatible(self, dist_op): ...
    def update_dims_mapping(self, dist_op): ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
