from ..completion import get_phi_spmd_rule as get_phi_spmd_rule
from ..utils import compute_compatible_and_update_dim_mapping as compute_compatible_and_update_dim_mapping, get_dist_tensor_spec as get_dist_tensor_spec, is_dim_shard as is_dim_shard
from .common import DistributedOperatorImpl as DistributedOperatorImpl, DistributedOperatorImplContainer as DistributedOperatorImplContainer, get_default_distributed_operator_impl as get_default_distributed_operator_impl, register_distributed_operator_impl as register_distributed_operator_impl, register_distributed_operator_impl_container as register_distributed_operator_impl_container, update_op_dims_mapping as update_op_dims_mapping
from .dist_default import DistributedDefaultImpl0 as DistributedDefaultImpl0

class DistributedSplit(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...
    @staticmethod
    def update_dims_mapping(dist_op): ...
    @staticmethod
    def mapping_to_dist_operator_impl(dist_op, original_op_dist_attr): ...

class DistributedSplitImpl(DistributedOperatorImpl):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op): ...
    def is_output_compatible(self, dist_op): ...
    def is_compatible(self, dist_op): ...
    def update_dims_mapping(self, dist_op): ...
    def is_auto_compatible(self, dist_op): ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
