from ..dist_attribute import OperatorDistAttr as OperatorDistAttr
from ..process_group import new_process_group as new_process_group
from ..utils import set_dist_op_desc_original_id as set_dist_op_desc_original_id, set_var_dist_attr as set_var_dist_attr
from .common import DistributedOperatorImpl as DistributedOperatorImpl, DistributedOperatorImplContainer as DistributedOperatorImplContainer, SyncMode as SyncMode, register_distributed_operator_impl as register_distributed_operator_impl, register_distributed_operator_impl_container as register_distributed_operator_impl_container
from _typeshed import Incomplete
from paddle.distributed.auto_parallel.static.process_group import get_world_process_group as get_world_process_group
from paddle.distributed.fleet.meta_optimizers.common import OP_ROLE_KEY as OP_ROLE_KEY, OpRole as OpRole
from paddle.framework import core as core

world_process_group: Incomplete

class DistributedCheckFiniteAndUnscale(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...

class DistributedCheckFiniteAndUnscaleImpl(DistributedOperatorImpl):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op) -> None: ...
    def is_output_compatible(self, dist_op) -> None: ...
    def is_auto_compatible(self, dist_op) -> None: ...
    def update_dims_mapping(self, dist_op) -> None: ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
