from ...random import determinate_rng as determinate_rng, is_enable_auto_rand_ctrl as is_enable_auto_rand_ctrl
from ..utils import naive_set_dist_op_attr_for_program_by_mesh_and_mapping as naive_set_dist_op_attr_for_program_by_mesh_and_mapping, set_var_dist_attr as set_var_dist_attr
from .common import DistributedOperatorImplContainer as DistributedOperatorImplContainer, register_distributed_operator_impl as register_distributed_operator_impl, register_distributed_operator_impl_container as register_distributed_operator_impl_container
from .dist_eltwise import DistributedDefaultImpl0 as DistributedDefaultImpl0, DistributedElementwiseImpl0 as DistributedElementwiseImpl0
from paddle.base.log_helper import get_logger as get_logger
from paddle.framework import core as core
from paddle.utils import unique_name as unique_name

class DistributedDropout(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...

class DistributedDropoutImpl0(DistributedElementwiseImpl0):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op): ...
    def is_output_compatible(self, dist_op): ...
    def is_auto_compatible(self, dist_op): ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
