from ..utils import set_dist_op_desc_original_id as set_dist_op_desc_original_id
from .common import DistributedOperatorImpl as DistributedOperatorImpl, DistributedOperatorImplContainer as DistributedOperatorImplContainer, register_distributed_operator_impl as register_distributed_operator_impl, register_distributed_operator_impl_container as register_distributed_operator_impl_container

class DistributedUpdateLossScaling(DistributedOperatorImplContainer):
    def __init__(self, op_type) -> None: ...

class DistributedUpdateLossScalingImpl(DistributedOperatorImpl):
    def __init__(self, name) -> None: ...
    def is_input_compatible(self, dist_op) -> None: ...
    def is_output_compatible(self, dist_op) -> None: ...
    def is_auto_compatible(self, dist_op) -> None: ...
    def update_dims_mapping(self, dist_op) -> None: ...
    @staticmethod
    def forward(ctx, *args, **kwargs) -> None: ...
    @staticmethod
    def backward(ctx, *args, **kwargs) -> None: ...
