from _typeshed import Incomplete

def log(ctx) -> None: ...
def process_args(ctx) -> None: ...
def collective_compatible(ctx) -> None: ...
def rewrite_host_ip(ctx) -> None: ...
def test_mode(ctx) -> None: ...

enabled_plugins: Incomplete
