from _typeshed import Incomplete
from paddle import nn as nn

class BaseGate(nn.Layer):
    world_size: Incomplete
    num_expert: Incomplete
    tot_expert: Incomplete
    loss: Incomplete
    def __init__(self, num_expert, world_size) -> None: ...
    def forward(self, x) -> None: ...
    def set_loss(self, loss) -> None: ...
    def get_loss(self, clear: bool = True): ...
